//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CIPAOnLine.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Emails {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Emails() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CIPAOnLine.Resources.Emails", typeof(Emails).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///	&lt;title&gt;CIPA&lt;/title&gt;
        ///	&lt;style type=&quot;text/css&quot;&gt;
        ///		* {{
        ///			font-size: 14px;
        ///			line-height: 1.428;
        ///			font-family: &quot;Segoe UI&quot;,Arial,sans-serif;
        ///		}}
        ///	&lt;/style&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///
        ///	&lt;h3&gt;Sua candidatura à eleição para {0} foi aprovada!&lt;/h3&gt;
        ///	&lt;p&gt;
        ///		&lt;strong&gt;CPF: &lt;/strong&gt;{1}&lt;br&gt;
        ///		&lt;strong&gt;Nome: &lt;/strong&gt;{2}&lt;br&gt;
        ///		&lt;strong&gt;Cargo: &lt;/strong&gt;{3}&lt;br&gt;
        ///		&lt;strong&gt;Área: &lt;/strong&gt;{4}
        ///	&lt;/p&gt;
        ///&lt;p style=&quot;color: #888&quot;&gt;
        ///Atenciosamente,&lt;br&gt;
        ///Sistema de Votação Online.
        ///&lt;/p&gt;
        ///&lt;/body&gt;
        ///&lt;/ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EmailAprovacaoCandidatura {
            get {
                return ResourceManager.GetString("EmailAprovacaoCandidatura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///	&lt;title&gt;CIPA&lt;/title&gt;
        ///	&lt;style type=&quot;text/css&quot;&gt;
        ///		* {{
        ///			font-size: 14px;
        ///			line-height: 1.428;
        ///			font-family: &quot;Segoe UI&quot;,Arial,sans-serif;
        ///		}}
        ///	&lt;/style&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///	&lt;h4&gt;ATA DE APURAÇÃO DOS VOTOS CIPA {0} GESTÃO {1}&lt;/h4&gt;
        ///	&lt;p&gt;Aos {2}, no(a) {3}, situado(a) no(a) {4}, nesta cidade {0}, diante a apuração ficou constatada a participação superior a cinquenta por cento dos empregados na votação, eximindo-se a empresa de nova votação, de acordo com o item 5.41 da N [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EmailApuracao {
            get {
                return ResourceManager.GetString("EmailApuracao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///	&lt;title&gt;CIPA&lt;/title&gt;
        ///	&lt;style type=&quot;text/css&quot;&gt;
        ///		* {{
        ///			font-size: 14px;
        ///			line-height: 1.428;
        ///			font-family: &quot;Segoe UI&quot;,Arial,sans-serif;
        ///		}}
        ///	&lt;/style&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///	&lt;h4&gt;RELAÇÃO DE CANDIDATOS INSCRITOS DA CIPA {0} – GESTÃO {1}&lt;/h4&gt;                                           
        ///	&lt;p&gt;Ficam convocados os associados, estagiários e temporários do(a) {2}, {3}, na cidade {0}, para a eleição de seus representantes na Comissão Interna de Prevenção de Acidentes - CIPA, de [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EmailCandidatos {
            get {
                return ResourceManager.GetString("EmailCandidatos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///	&lt;title&gt;CIPA&lt;/title&gt;
        ///	&lt;style type=&quot;text/css&quot;&gt;
        ///		* {{
        ///			font-size: 14px;
        ///			line-height: 1.428;
        ///			font-family: &quot;Segoe UI&quot;,Arial,sans-serif;
        ///		}}
        ///	&lt;/style&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///
        ///	&lt;h3&gt;Sua candidatura à eleicão para {0} foi efetuada com sucesso!&lt;/h3&gt;
        ///	&lt;p&gt;
        ///		&lt;strong&gt;CPF: &lt;/strong&gt;{1}&lt;br&gt;
        ///		&lt;strong&gt;Nome: &lt;/strong&gt;{2}&lt;br&gt;
        ///		&lt;strong&gt;Cargo: &lt;/strong&gt;{3}&lt;br&gt;
        ///		&lt;strong&gt;Área: &lt;/strong&gt;{4}
        ///	&lt;/p&gt;
        ///	&lt;p&gt;Agora, sua candidatura passará pela aprovação dos responsáveis pelo process [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EmailCandidatura {
            get {
                return ResourceManager.GetString("EmailCandidatura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///	&lt;title&gt;CIPA&lt;/title&gt;
        ///	&lt;style type=&quot;text/css&quot;&gt;
        ///		* {{
        ///			font-size: 14px;
        ///			line-height: 1.428;
        ///			font-family: &quot;Segoe UI&quot;,Arial,sans-serif;
        ///		}}
        ///
        ///		.email p {{
        ///			text-indent: 20px;
        ///		}}
        ///
        ///		div.footer {{
        ///			margin-left: 30px;
        ///		}}
        ///
        ///	&lt;/style&gt;
        ///
        ///	&lt;!-- Custom Fonts --&gt;
        ///    &lt;link rel=&quot;stylesheet&quot; type=&quot;text/css&quot; href=&quot;https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css&quot;&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///
        ///	&lt;div class=&quot;email&quot;&gt;
        ///		&lt;p&gt;{0}, &lt;strong&gt;{1}&lt;/s [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EmailEdital {
            get {
                return ResourceManager.GetString("EmailEdital", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eleicoes.cipa@gmail.com.
        /// </summary>
        internal static string EmailEndereco {
            get {
                return ResourceManager.GetString("EmailEndereco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///	&lt;title&gt;CIPA&lt;/title&gt;
        ///	&lt;style type=&quot;text/css&quot;&gt;
        ///		* {{
        ///			font-size: 14px;
        ///			line-height: 1.428;
        ///			font-family: &quot;Segoe UI&quot;,Arial,sans-serif;
        ///		}}
        ///	&lt;/style&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///	&lt;h4&gt;EDITAL DE INSCRIÇÃO PARA MEMBROS DA CIPA {0} – GESTÃO {1}&lt;/h4&gt;
        ///	&lt;p&gt;Aos {2}, o(a) {3}, situado(a) no(a) {4}, nesta cidade de {0}, site ......, convida seus associados a realizarem suas inscrições para eleição dos membros representantes dos Empregados da Comissão Interna de Prevenção de Aciden [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EmailInscricao {
            get {
                return ResourceManager.GetString("EmailInscricao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to votacaoonline@algartech.com.
        /// </summary>
        internal static string EmailOrigem {
            get {
                return ResourceManager.GetString("EmailOrigem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;Olá!&lt;/strong&gt;&lt;br&gt;&lt;br&gt;Recuperamos sua senha de acesso ao sistema de Votação Online: {0}..
        /// </summary>
        internal static string EmailRecuperacaoSenha {
            get {
                return ResourceManager.GetString("EmailRecuperacaoSenha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///	&lt;title&gt;CIPA&lt;/title&gt;
        ///	&lt;style type=&quot;text/css&quot;&gt;
        ///		* {{
        ///			font-size: 14px;
        ///			line-height: 1.428;
        ///			font-family: &quot;Segoe UI&quot;,Arial,sans-serif;
        ///		}}
        ///	&lt;/style&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///
        ///	&lt;h3&gt;Sua candidatura à eleição para {0} foi reprovada.&lt;/h3&gt;
        ///	&lt;p&gt;
        ///		&lt;strong&gt;CPF: &lt;/strong&gt;{1}&lt;br&gt;
        ///		&lt;strong&gt;Nome: &lt;/strong&gt;{2}&lt;br&gt;
        ///		&lt;strong&gt;Cargo: &lt;/strong&gt;{3}&lt;br&gt;
        ///		&lt;strong&gt;Área: &lt;/strong&gt;{4}
        ///	&lt;/p&gt;
        ///	&lt;p&gt;Segue abaixo o motivo informado pelo administrador do processo eleitoral:&lt;/p&gt;
        ///	&lt;p sty [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EmailReprovacaoCandidatura {
            get {
                return ResourceManager.GetString("EmailReprovacaoCandidatura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *eleicoes.cipa*.
        /// </summary>
        internal static string EmailSenha {
            get {
                return ResourceManager.GetString("EmailSenha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///	&lt;title&gt;CIPA&lt;/title&gt;
        ///	&lt;style type=&quot;text/css&quot;&gt;
        ///		* {{
        ///			font-size: 14px;
        ///			line-height: 1.428;
        ///			font-family: &quot;Segoe UI&quot;,Arial,sans-serif;
        ///		}}
        ///
        ///		.email p {{
        ///			text-indent: 20px;
        ///		}}
        ///
        ///		div.footer {{
        ///			margin-left: 20px;
        ///		}}
        ///
        ///		div.title {{
        ///			margin-left: 20px;
        ///		}}
        ///
        ///		#cronograma {{
        ///			padding-left: 20px;
        ///		}}
        ///
        ///	&lt;/style&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///
        ///	&lt;div class=&quot;email&quot;&gt;
        ///		&lt;p&gt;{0}, {1}.&lt;/p&gt;
        ///
        ///		&lt;div class=&quot;title&quot;&gt;
        ///			Finalidade: Comunicação de eleiçõ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EmailSindicato {
            get {
                return ResourceManager.GetString("EmailSindicato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///	&lt;title&gt;CIPA&lt;/title&gt;
        ///	&lt;style type=&quot;text/css&quot;&gt;
        ///		* {{
        ///			font-size: 14px;
        ///			line-height: 1.428;
        ///			font-family: &quot;Segoe UI&quot;,Arial,sans-serif;
        ///		}}
        ///	&lt;/style&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///	&lt;h4&gt;EDITAL DE VOTAÇÃO PARA MEMBROS DA CIPA {0} – GESTÃO {1}&lt;/h4&gt; 
        ///	&lt;p&gt;Aos {2}, o(a) {3}, situado(a) no(a) {4}, nesta cidade de {0}, através de seu SESMT – Serviço Especializado em Engenharia de Segurança e Medicina do Trabalho - INFORMAMOS A TODOS OS ASSOCIADOS QUE O PROCESSO DE VOTAÇÃO DA CIPA  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EmailVotacao {
            get {
                return ResourceManager.GetString("EmailVotacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://10.200.51.46:8090.
        /// </summary>
        internal static string LinkSistema {
            get {
                return ResourceManager.GetString("LinkSistema", resourceCulture);
            }
        }
    }
}
