namespace CIPAOnLine.Migrations
{
    using System;
    using System.Collections.Generic;
    using System.Data.Entity;
    using System.Data.Entity.Migrations;
    using System.Linq;
    using CIPAOnLine.DTO;
    using CIPAOnLine.Models;
    using CIPAOnLine.Services;

    internal sealed class Configuration : DbMigrationsConfiguration<Modelo>
    {
        public Configuration()
        {
            AutomaticMigrationsEnabled = false;
        }

        protected override void Seed(Modelo context)
        {
            context.Empresas.AddOrUpdate(e => e.Codigo,
                new Empresa { Codigo = 9, RazaoSocial = "ALGAR SEGURANCA ELETRONICA E SERVICOS LTDA" },
                new Empresa { Codigo = 10, RazaoSocial = "ALGAR SEGURANCA E VIGILANCIA LTDA" },
                new Empresa { Codigo = 15, RazaoSocial = "ALGAR S/A EMPREENDIMENTOS E PARTICIPACOES" },
                new Empresa { Codigo = 18, RazaoSocial = "ABC AGRICULTURA E PECUARIA SA- ABC A&P" },
                new Empresa { Codigo = 20, RazaoSocial = "ABC AGROPEC BRASIL NORTE S/A PROD EXPORT" },
                new Empresa { Codigo = 25, RazaoSocial = "ALGAR TELECOM S/A" },
                new Empresa { Codigo = 27, RazaoSocial = "ALGAR MULTIMIDIA S/A" },
                new Empresa { Codigo = 28, RazaoSocial = "ENGESET ENG SERV TELECOMUNICACOES SA" },
                new Empresa { Codigo = 29, RazaoSocial = "ALGAR TECNOLOGIA E CONSULTORIA S/A" },
                new Empresa { Codigo = 33, RazaoSocial = "ALGAR TI CONSULTORIA S/A" },
                new Empresa { Codigo = 38, RazaoSocial = "ALGAR SOLUCOES EM TIC S/A" },
                new Empresa { Codigo = 39, RazaoSocial = "ALSOL ENERGIAS RENOVAVEIS S/A" });

            context.Usuarios.AddOrUpdate(u => u.Login,
                new Usuario {
                    Login = "admin", Nome = "Administrador Master", Perfil = Perfil.ADMINISTRADOR, Senha = CryptoGraph.Encrypt("Admin01!")
                }
            );

            context.Modulos.AddOrUpdate(x => x.Codigo,
                new Modulo { Codigo = 1, NomeModulo = "CIPA" },
                new Modulo { Codigo = 2, NomeModulo = "Comissão Interna de Trabalhadores" }
            );

            List<TemplateEmail> templates = new List<TemplateEmail>()
            {
                new TemplateEmail() { Template = Resources.Emails.EmailEdital, Nome = "[CIPA] Edital do Processo" },
                new TemplateEmail() { Template = Resources.Emails.EmailSindicato, Nome = "[CIPA] Comunicação ao Sindicato" },
                new TemplateEmail() { Template = Resources.Emails.EmailInscricoes, Nome = "[CIPA] Inscrições para CIPA" },
                new TemplateEmail() { Template = Resources.Emails.EmailCandidatos, Nome = "[CIPA] Relação de Candidatos" },
                new TemplateEmail() { Template = Resources.Emails.EmailVotacao, Nome = "[CIPA] Convite para Votação" },
                new TemplateEmail() { Template = Resources.Emails.EmailApuracaoVotos, Nome = "[CIPA] Apuração dos Votos" }
            };

            templates.ForEach(t =>
            {
                if (!context.Templates.Any(x => x.Nome == t.Nome))
                    context.Templates.Add(t);
            });

            context.Grupos.AddOrUpdate(
                new Grupo() { Codigo = "C-1" },
                new Grupo() { Codigo = "C-10" },
                new Grupo() { Codigo = "C-11" },
                new Grupo() { Codigo = "C-12" },
                new Grupo() { Codigo = "C-13" },
                new Grupo() { Codigo = "C-14" },
                new Grupo() { Codigo = "C-14a" },
                new Grupo() { Codigo = "C-15" },
                new Grupo() { Codigo = "C-16" },
                new Grupo() { Codigo = "C-17" },
                new Grupo() { Codigo = "C-18" },
                new Grupo() { Codigo = "C-18a" },
                new Grupo() { Codigo = "C-19" },
                new Grupo() { Codigo = "C-1a" },
                new Grupo() { Codigo = "C-2" },
                new Grupo() { Codigo = "C-20" },
                new Grupo() { Codigo = "C-21" },
                new Grupo() { Codigo = "C-22" },
                new Grupo() { Codigo = "C-23" },
                new Grupo() { Codigo = "C-24" },
                new Grupo() { Codigo = "C-24a" },
                new Grupo() { Codigo = "C-24b" },
                new Grupo() { Codigo = "C-25" },
                new Grupo() { Codigo = "C-26" },
                new Grupo() { Codigo = "C-27" },
                new Grupo() { Codigo = "C-28" },
                new Grupo() { Codigo = "C-29" },
                new Grupo() { Codigo = "C-3" },
                new Grupo() { Codigo = "C-30" },
                new Grupo() { Codigo = "C-31" },
                new Grupo() { Codigo = "C-32" },
                new Grupo() { Codigo = "C-33" },
                new Grupo() { Codigo = "C-34" },
                new Grupo() { Codigo = "C-35" },
                new Grupo() { Codigo = "C-3a" },
                new Grupo() { Codigo = "C-4" },
                new Grupo() { Codigo = "C-5" },
                new Grupo() { Codigo = "C-5a" },
                new Grupo() { Codigo = "C-6" },
                new Grupo() { Codigo = "C-7" },
                new Grupo() { Codigo = "C-7a" },
                new Grupo() { Codigo = "C-8" },
                new Grupo() { Codigo = "C-9" }
            );

            context.AcrescimosLimites.AddOrUpdate(
                new AcrescimoLimite() { CodigoGrupo = "C-1", Efetivo = true, QtdaLimite = 10000, IntervaloLimite = 2500, QtdaAcrescimo = 2 },
                new AcrescimoLimite() { CodigoGrupo = "C-1", Efetivo = false, QtdaLimite = 10000, IntervaloLimite = 2500, QtdaAcrescimo = 2 },
                new AcrescimoLimite() { CodigoGrupo = "C-1a", Efetivo = true, QtdaLimite = 10000, IntervaloLimite = 2500, QtdaAcrescimo = 2 },
                new AcrescimoLimite() { CodigoGrupo = "C-1a", Efetivo = false, QtdaLimite = 10000, IntervaloLimite = 2500, QtdaAcrescimo = 2 },
                new AcrescimoLimite() { CodigoGrupo = "C-2", Efetivo = true, QtdaLimite = 10000, IntervaloLimite = 2500, QtdaAcrescimo = 2 },
                new AcrescimoLimite() { CodigoGrupo = "C-2", Efetivo = false, QtdaLimite = 10000, IntervaloLimite = 2500, QtdaAcrescimo = 1 },
                new AcrescimoLimite() { CodigoGrupo = "C-3", Efetivo = true, QtdaLimite = 10000, IntervaloLimite = 2500, QtdaAcrescimo = 2 },
                new AcrescimoLimite() { CodigoGrupo = "C-3", Efetivo = false, QtdaLimite = 10000, IntervaloLimite = 2500, QtdaAcrescimo = 2 },
                new AcrescimoLimite() { CodigoGrupo = "C-3a", Efetivo = true, QtdaLimite = 10000, IntervaloLimite = 2500, QtdaAcrescimo = 1 },
                new AcrescimoLimite() { CodigoGrupo = "C-3a", Efetivo = false, QtdaLimite = 10000, IntervaloLimite = 2500, QtdaAcrescimo = 1 },
                new AcrescimoLimite() { CodigoGrupo = "C-4", Efetivo = true, QtdaLimite = 10000, IntervaloLimite = 2500, QtdaAcrescimo = 1 },
                new AcrescimoLimite() { CodigoGrupo = "C-4", Efetivo = false, QtdaLimite = 10000, IntervaloLimite = 2500, QtdaAcrescimo = 1 },
                new AcrescimoLimite() { CodigoGrupo = "C-5", Efetivo = true, QtdaLimite = 10000, IntervaloLimite = 2500, QtdaAcrescimo = 2 },
                new AcrescimoLimite() { CodigoGrupo = "C-5", Efetivo = false, QtdaLimite = 10000, IntervaloLimite = 2500, QtdaAcrescimo = 2 },
                new AcrescimoLimite() { CodigoGrupo = "C-5a", Efetivo = true, QtdaLimite = 10000, IntervaloLimite = 2500, QtdaAcrescimo = 1 },
                new AcrescimoLimite() { CodigoGrupo = "C-5a", Efetivo = false, QtdaLimite = 10000, IntervaloLimite = 2500, QtdaAcrescimo = 1 },
                new AcrescimoLimite() { CodigoGrupo = "C-6", Efetivo = true, QtdaLimite = 10000, IntervaloLimite = 2500, QtdaAcrescimo = 2 },
                new AcrescimoLimite() { CodigoGrupo = "C-6", Efetivo = false, QtdaLimite = 10000, IntervaloLimite = 2500, QtdaAcrescimo = 2 },
                new AcrescimoLimite() { CodigoGrupo = "C-7", Efetivo = true, QtdaLimite = 10000, IntervaloLimite = 2500, QtdaAcrescimo = 1 },
                new AcrescimoLimite() { CodigoGrupo = "C-7", Efetivo = false, QtdaLimite = 10000, IntervaloLimite = 2500, QtdaAcrescimo = 1 },
                new AcrescimoLimite() { CodigoGrupo = "C-7a", Efetivo = true, QtdaLimite = 10000, IntervaloLimite = 2500, QtdaAcrescimo = 2 },
                new AcrescimoLimite() { CodigoGrupo = "C-7a", Efetivo = false, QtdaLimite = 10000, IntervaloLimite = 2500, QtdaAcrescimo = 2 },
                new AcrescimoLimite() { CodigoGrupo = "C-8", Efetivo = true, QtdaLimite = 10000, IntervaloLimite = 2500, QtdaAcrescimo = 1 },
                new AcrescimoLimite() { CodigoGrupo = "C-8", Efetivo = false, QtdaLimite = 10000, IntervaloLimite = 2500, QtdaAcrescimo = 1 },
                new AcrescimoLimite() { CodigoGrupo = "C-9", Efetivo = true, QtdaLimite = 10000, IntervaloLimite = 2500, QtdaAcrescimo = 1 },
                new AcrescimoLimite() { CodigoGrupo = "C-9", Efetivo = false, QtdaLimite = 10000, IntervaloLimite = 2500, QtdaAcrescimo = 1 },
                new AcrescimoLimite() { CodigoGrupo = "C-10", Efetivo = true, QtdaLimite = 10000, IntervaloLimite = 2500, QtdaAcrescimo = 2 },
                new AcrescimoLimite() { CodigoGrupo = "C-10", Efetivo = false, QtdaLimite = 10000, IntervaloLimite = 2500, QtdaAcrescimo = 2 },
                new AcrescimoLimite() { CodigoGrupo = "C-11", Efetivo = true, QtdaLimite = 10000, IntervaloLimite = 2500, QtdaAcrescimo = 2 },
                new AcrescimoLimite() { CodigoGrupo = "C-11", Efetivo = false, QtdaLimite = 10000, IntervaloLimite = 2500, QtdaAcrescimo = 2 },
                new AcrescimoLimite() { CodigoGrupo = "C-12", Efetivo = true, QtdaLimite = 10000, IntervaloLimite = 2500, QtdaAcrescimo = 2 },
                new AcrescimoLimite() { CodigoGrupo = "C-12", Efetivo = false, QtdaLimite = 10000, IntervaloLimite = 2500, QtdaAcrescimo = 2 },
                new AcrescimoLimite() { CodigoGrupo = "C-13", Efetivo = true, QtdaLimite = 10000, IntervaloLimite = 2500, QtdaAcrescimo = 2 },
                new AcrescimoLimite() { CodigoGrupo = "C-13", Efetivo = false, QtdaLimite = 10000, IntervaloLimite = 2500, QtdaAcrescimo = 2 },
                new AcrescimoLimite() { CodigoGrupo = "C-14", Efetivo = true, QtdaLimite = 10000, IntervaloLimite = 2500, QtdaAcrescimo = 2 },
                new AcrescimoLimite() { CodigoGrupo = "C-14", Efetivo = false, QtdaLimite = 10000, IntervaloLimite = 2500, QtdaAcrescimo = 2 },
                new AcrescimoLimite() { CodigoGrupo = "C-14a", Efetivo = true, QtdaLimite = 10000, IntervaloLimite = 2500, QtdaAcrescimo = 1 },
                new AcrescimoLimite() { CodigoGrupo = "C-14a", Efetivo = false, QtdaLimite = 10000, IntervaloLimite = 2500, QtdaAcrescimo = 1 },
                new AcrescimoLimite() { CodigoGrupo = "C-15", Efetivo = true, QtdaLimite = 10000, IntervaloLimite = 2500, QtdaAcrescimo = 2 },
                new AcrescimoLimite() { CodigoGrupo = "C-15", Efetivo = false, QtdaLimite = 10000, IntervaloLimite = 2500, QtdaAcrescimo = 2 },
                new AcrescimoLimite() { CodigoGrupo = "C-16", Efetivo = true, QtdaLimite = 10000, IntervaloLimite = 2500, QtdaAcrescimo = 2 },
                new AcrescimoLimite() { CodigoGrupo = "C-16", Efetivo = false, QtdaLimite = 10000, IntervaloLimite = 2500, QtdaAcrescimo = 2 },
                new AcrescimoLimite() { CodigoGrupo = "C-17", Efetivo = true, QtdaLimite = 10000, IntervaloLimite = 2500, QtdaAcrescimo = 2 },
                new AcrescimoLimite() { CodigoGrupo = "C-17", Efetivo = false, QtdaLimite = 10000, IntervaloLimite = 2500, QtdaAcrescimo = 2 },
                new AcrescimoLimite() { CodigoGrupo = "C-18", Efetivo = true, QtdaLimite = 10000, IntervaloLimite = 2500, QtdaAcrescimo = 2 },
                new AcrescimoLimite() { CodigoGrupo = "C-18", Efetivo = false, QtdaLimite = 10000, IntervaloLimite = 2500, QtdaAcrescimo = 2 },
                new AcrescimoLimite() { CodigoGrupo = "C-18a", Efetivo = true, QtdaLimite = 10000, IntervaloLimite = 2500, QtdaAcrescimo = 2 },
                new AcrescimoLimite() { CodigoGrupo = "C-18a", Efetivo = false, QtdaLimite = 10000, IntervaloLimite = 2500, QtdaAcrescimo = 2 },
                new AcrescimoLimite() { CodigoGrupo = "C-19", Efetivo = true, QtdaLimite = 10000, IntervaloLimite = 2500, QtdaAcrescimo = 1 },
                new AcrescimoLimite() { CodigoGrupo = "C-19", Efetivo = false, QtdaLimite = 10000, IntervaloLimite = 2500, QtdaAcrescimo = 1 },
                new AcrescimoLimite() { CodigoGrupo = "C-20", Efetivo = true, QtdaLimite = 10000, IntervaloLimite = 2500, QtdaAcrescimo = 2 },
                new AcrescimoLimite() { CodigoGrupo = "C-20", Efetivo = false, QtdaLimite = 10000, IntervaloLimite = 2500, QtdaAcrescimo = 1 },
                new AcrescimoLimite() { CodigoGrupo = "C-21", Efetivo = true, QtdaLimite = 10000, IntervaloLimite = 2500, QtdaAcrescimo = 1 },
                new AcrescimoLimite() { CodigoGrupo = "C-21", Efetivo = false, QtdaLimite = 10000, IntervaloLimite = 2500, QtdaAcrescimo = 1 },
                new AcrescimoLimite() { CodigoGrupo = "C-22", Efetivo = true, QtdaLimite = 10000, IntervaloLimite = 2500, QtdaAcrescimo = 2 },
                new AcrescimoLimite() { CodigoGrupo = "C-22", Efetivo = false, QtdaLimite = 10000, IntervaloLimite = 2500, QtdaAcrescimo = 2 },
                new AcrescimoLimite() { CodigoGrupo = "C-23", Efetivo = true, QtdaLimite = 10000, IntervaloLimite = 2500, QtdaAcrescimo = 1 },
                new AcrescimoLimite() { CodigoGrupo = "C-23", Efetivo = false, QtdaLimite = 10000, IntervaloLimite = 2500, QtdaAcrescimo = 1 },
                new AcrescimoLimite() { CodigoGrupo = "C-24", Efetivo = true, QtdaLimite = 10000, IntervaloLimite = 2500, QtdaAcrescimo = 2 },
                new AcrescimoLimite() { CodigoGrupo = "C-24", Efetivo = false, QtdaLimite = 10000, IntervaloLimite = 2500, QtdaAcrescimo = 2 },
                new AcrescimoLimite() { CodigoGrupo = "C-24a", Efetivo = true, QtdaLimite = 10000, IntervaloLimite = 2500, QtdaAcrescimo = 1 },
                new AcrescimoLimite() { CodigoGrupo = "C-24a", Efetivo = false, QtdaLimite = 10000, IntervaloLimite = 2500, QtdaAcrescimo = 1 },
                new AcrescimoLimite() { CodigoGrupo = "C-24b", Efetivo = true, QtdaLimite = 10000, IntervaloLimite = 2500, QtdaAcrescimo = 2 },
                new AcrescimoLimite() { CodigoGrupo = "C-24b", Efetivo = false, QtdaLimite = 10000, IntervaloLimite = 2500, QtdaAcrescimo = 2 },
                new AcrescimoLimite() { CodigoGrupo = "C-25", Efetivo = true, QtdaLimite = 10000, IntervaloLimite = 2500, QtdaAcrescimo = 1 },
                new AcrescimoLimite() { CodigoGrupo = "C-25", Efetivo = false, QtdaLimite = 10000, IntervaloLimite = 2500, QtdaAcrescimo = 1 },
                new AcrescimoLimite() { CodigoGrupo = "C-26", Efetivo = true, QtdaLimite = 10000, IntervaloLimite = 2500, QtdaAcrescimo = 1 },
                new AcrescimoLimite() { CodigoGrupo = "C-26", Efetivo = false, QtdaLimite = 10000, IntervaloLimite = 2500, QtdaAcrescimo = 1 },
                new AcrescimoLimite() { CodigoGrupo = "C-27", Efetivo = true, QtdaLimite = 10000, IntervaloLimite = 2500, QtdaAcrescimo = 1 },
                new AcrescimoLimite() { CodigoGrupo = "C-27", Efetivo = false, QtdaLimite = 10000, IntervaloLimite = 2500, QtdaAcrescimo = 1 },
                new AcrescimoLimite() { CodigoGrupo = "C-28", Efetivo = true, QtdaLimite = 10000, IntervaloLimite = 2500, QtdaAcrescimo = 1 },
                new AcrescimoLimite() { CodigoGrupo = "C-28", Efetivo = false, QtdaLimite = 10000, IntervaloLimite = 2500, QtdaAcrescimo = 1 },
                new AcrescimoLimite() { CodigoGrupo = "C-29", Efetivo = true, QtdaLimite = 10000, IntervaloLimite = 2500, QtdaAcrescimo = 1 },
                new AcrescimoLimite() { CodigoGrupo = "C-29", Efetivo = false, QtdaLimite = 10000, IntervaloLimite = 2500, QtdaAcrescimo = 1 },
                new AcrescimoLimite() { CodigoGrupo = "C-30", Efetivo = true, QtdaLimite = 10000, IntervaloLimite = 2500, QtdaAcrescimo = 2 },
                new AcrescimoLimite() { CodigoGrupo = "C-30", Efetivo = false, QtdaLimite = 10000, IntervaloLimite = 2500, QtdaAcrescimo = 1 },
                new AcrescimoLimite() { CodigoGrupo = "C-31", Efetivo = true, QtdaLimite = 10000, IntervaloLimite = 2500, QtdaAcrescimo = 1 },
                new AcrescimoLimite() { CodigoGrupo = "C-31", Efetivo = false, QtdaLimite = 10000, IntervaloLimite = 2500, QtdaAcrescimo = 1 },
                new AcrescimoLimite() { CodigoGrupo = "C-32", Efetivo = true, QtdaLimite = 10000, IntervaloLimite = 2500, QtdaAcrescimo = 1 },
                new AcrescimoLimite() { CodigoGrupo = "C-32", Efetivo = false, QtdaLimite = 10000, IntervaloLimite = 2500, QtdaAcrescimo = 1 },
                new AcrescimoLimite() { CodigoGrupo = "C-33", Efetivo = true, QtdaLimite = 10000, IntervaloLimite = 2500, QtdaAcrescimo = 1 },
                new AcrescimoLimite() { CodigoGrupo = "C-33", Efetivo = false, QtdaLimite = 10000, IntervaloLimite = 2500, QtdaAcrescimo = 1 },
                new AcrescimoLimite() { CodigoGrupo = "C-34", Efetivo = true, QtdaLimite = 10000, IntervaloLimite = 2500, QtdaAcrescimo = 2 },
                new AcrescimoLimite() { CodigoGrupo = "C-34", Efetivo = false, QtdaLimite = 10000, IntervaloLimite = 2500, QtdaAcrescimo = 2 },
                new AcrescimoLimite() { CodigoGrupo = "C-35", Efetivo = true, QtdaLimite = 10000, IntervaloLimite = 2500, QtdaAcrescimo = 1 },
                new AcrescimoLimite() { CodigoGrupo = "C-35", Efetivo = false, QtdaLimite = 10000, IntervaloLimite = 2500, QtdaAcrescimo = 1 }
            );

            context.Etapas.AddOrUpdate(
                new Etapa() { CodigoEtapa = 1, NomeEtapa = "EDITAL DE CONVOCAÇÃO PARA ELEIÇÃO", DiasPrazo = 2, CodigoModulo = 1, Ordem = 1 },
                new Etapa() { CodigoEtapa = 2, NomeEtapa = "FORMAÇÃO DA COMISSÃO ELEITORAL", DiasPrazo = 3, CodigoModulo = 1, Ordem = 2 },
                new Etapa() { CodigoEtapa = 3, NomeEtapa = "ENVIAR CÓPIA DO EDITAL DE CONVOCAÇÃO AO SINDICATO", DiasPrazo = 4, CodigoModulo = 1, Ordem = 3 },
                new Etapa() { CodigoEtapa = 6, NomeEtapa = "PUBLICAÇÃO EDITAL DE INSCRIÇÃO DE CANDIDATOS", DiasPrazo = 1, CodigoModulo = 1, Ordem = 4 },
                new Etapa() { CodigoEtapa = 4, NomeEtapa = "INÍCIO INSCRIÇÕES CANDIDATOS", DiasPrazo = 14, CodigoModulo = 1, Ordem = 5 },
                new Etapa() { CodigoEtapa = 5, NomeEtapa = "TÉRMINO INSCRIÇÕES CANDIDATOS", DiasPrazo = 3, CodigoModulo = 1, Ordem = 6 },
                new Etapa() { CodigoEtapa = 9, NomeEtapa = "REALIZAÇÃO DA ELEIÇÃO (VOTAÇÃO)", DiasPrazo = 20, CodigoModulo = 1, Ordem = 7 },
                new Etapa() { CodigoEtapa = 10, NomeEtapa = "REALIZAÇÃO DA APURAÇÃO", DiasPrazo = 3, CodigoModulo = 1, Ordem = 8 },
                new Etapa() { CodigoEtapa = 11, NomeEtapa = "RESULTADO DA ELEIÇÃO - ATA DA ELEIÇÃO", DiasPrazo = 1, CodigoModulo = 1, Ordem = 9 },
                new Etapa() { CodigoEtapa = 12, NomeEtapa = "CURSO PARA CIPEIROS (DATA MÍNIMA)", DiasPrazo = 20, CodigoModulo = 1, Ordem = 10 },
                new Etapa() { CodigoEtapa = 13, NomeEtapa = "CURSO PARA CIPEIROS (DATA MÁXIMA)", DiasPrazo = 4, CodigoModulo = 1, Ordem = 11 },
                new Etapa() { CodigoEtapa = 14, NomeEtapa = "TÉRMINO DO MANDATO ANTERIOR", DiasPrazo = 2, CodigoModulo = 1, Ordem = 12 },
                new Etapa() { CodigoEtapa = 15, NomeEtapa = "REALIZAÇÃO DA POSSE - ATA DE POSSE NOVOS MEMBROS", DiasPrazo = 1, CodigoModulo = 1, Ordem = 13 },
                new Etapa() { CodigoEtapa = 16, NomeEtapa = "ORGANIZAÇÃO DO CALENDÁRIO REUNIÕES MENSAIS", DiasPrazo = 1, CodigoModulo = 1, Ordem = 14 },
                new Etapa() { CodigoEtapa = 17, NomeEtapa = "EDITAL DE CONVOCAÇÃO PARA ELEIÇÃO", DiasPrazo = 2, CodigoModulo = 2, Ordem = 1 },
                new Etapa() { CodigoEtapa = 18, NomeEtapa = "FORMAÇÃO DA COMISSÃO ELEITORAL", DiasPrazo = 3, CodigoModulo = 2, Ordem = 2 },
                new Etapa() { CodigoEtapa = 30, NomeEtapa = "TÉRMINO DO MANDATO ANTERIOR", DiasPrazo = 2, CodigoModulo = 2, Ordem = 3 },
                new Etapa() { CodigoEtapa = 21, NomeEtapa = "PUBLICAÇÃO EDITAL DE INSCRIÇÃO DE CANDIDATOS", DiasPrazo = 1, CodigoModulo = 2, Ordem = 4 },
                new Etapa() { CodigoEtapa = 19, NomeEtapa = "INÍCIO INSCRIÇÕES CANDIDATOS", DiasPrazo = 14, CodigoModulo = 2, Ordem = 5 },
                new Etapa() { CodigoEtapa = 20, NomeEtapa = "TÉRMINO INSCRIÇÕES CANDIDATOS", DiasPrazo = 3, CodigoModulo = 2, Ordem = 6 },
                new Etapa() { CodigoEtapa = 24, NomeEtapa = "REALIZAÇÃO DA ELEIÇÃO (VOTAÇÃO)", DiasPrazo = 20, CodigoModulo = 2, Ordem = 7 },
                new Etapa() { CodigoEtapa = 25, NomeEtapa = "REALIZAÇÃO DA APURAÇÃO", DiasPrazo = 3, CodigoModulo = 2, Ordem = 8 },
                new Etapa() { CodigoEtapa = 26, NomeEtapa = "RESULTADO DA ELEIÇÃO - ATA DA ELEIÇÃO", DiasPrazo = 1, CodigoModulo = 2, Ordem = 9 },
                new Etapa() { CodigoEtapa = 28, NomeEtapa = "REALIZAÇÃO DA POSSE - ATA DE POSSE NOVOS MEMBROS", DiasPrazo = 1, CodigoModulo = 2, Ordem = 10 },
                new Etapa() { CodigoEtapa = 29, NomeEtapa = "ORGANIZAÇÃO DO CALENDÁRIO REUNIÕES MENSAIS", DiasPrazo = 1, CodigoModulo = 2, Ordem = 11 }
            );

            context.QtdasComissaoInterna.AddOrUpdate(
                new QtdaComissaoInterna() { QtdaMin = 0, Valor = 0 },
                new QtdaComissaoInterna() { QtdaMin = 200, Valor = 3 },
                new QtdaComissaoInterna() { QtdaMin = 3001, Valor = 5 },
                new QtdaComissaoInterna() { QtdaMin = 5001, Valor = 7 }
            );

            context.QtdasGrupos.AddOrUpdate(
                new QtdaGrupo() { CodigoGrupo = "C-1", Efetivo = true, QtdaMin = 0, QtdaMax = 19, Valor = 0 },
                new QtdaGrupo() { CodigoGrupo = "C-1", Efetivo = true, QtdaMin = 20, QtdaMax = 50, Valor = 1 },
                new QtdaGrupo() { CodigoGrupo = "C-1", Efetivo = true, QtdaMin = 51, QtdaMax = 100, Valor = 3 },
                new QtdaGrupo() { CodigoGrupo = "C-1", Efetivo = true, QtdaMin = 101, QtdaMax = 500, Valor = 4 },
                new QtdaGrupo() { CodigoGrupo = "C-1", Efetivo = true, QtdaMin = 501, QtdaMax = 1000, Valor = 6 },
                new QtdaGrupo() { CodigoGrupo = "C-1", Efetivo = true, QtdaMin = 1001, QtdaMax = 2500, Valor = 9 },
                new QtdaGrupo() { CodigoGrupo = "C-1", Efetivo = true, QtdaMin = 2501, QtdaMax = 5000, Valor = 12 },
                new QtdaGrupo() { CodigoGrupo = "C-1", Efetivo = true, QtdaMin = 5001, QtdaMax = 10000, Valor = 15 },
                new QtdaGrupo() { CodigoGrupo = "C-1", Efetivo = false, QtdaMin = 0, QtdaMax = 19, Valor = 0 },
                new QtdaGrupo() { CodigoGrupo = "C-1", Efetivo = false, QtdaMin = 20, QtdaMax = 50, Valor = 1 },
                new QtdaGrupo() { CodigoGrupo = "C-1", Efetivo = false, QtdaMin = 51, QtdaMax = 500, Valor = 3 },
                new QtdaGrupo() { CodigoGrupo = "C-1", Efetivo = false, QtdaMin = 501, QtdaMax = 1000, Valor = 4 },
                new QtdaGrupo() { CodigoGrupo = "C-1", Efetivo = false, QtdaMin = 1001, QtdaMax = 2500, Valor = 7 },
                new QtdaGrupo() { CodigoGrupo = "C-1", Efetivo = false, QtdaMin = 2501, QtdaMax = 5000, Valor = 9 },
                new QtdaGrupo() { CodigoGrupo = "C-1", Efetivo = false, QtdaMin = 5001, QtdaMax = 10000, Valor = 12 },
                new QtdaGrupo() { CodigoGrupo = "C-1a", Efetivo = true, QtdaMin = 0, QtdaMax = 19, Valor = 0 },
                new QtdaGrupo() { CodigoGrupo = "C-1a", Efetivo = true, QtdaMin = 20, QtdaMax = 50, Valor = 1 },
                new QtdaGrupo() { CodigoGrupo = "C-1a", Efetivo = true, QtdaMin = 51, QtdaMax = 100, Valor = 3 },
                new QtdaGrupo() { CodigoGrupo = "C-1a", Efetivo = true, QtdaMin = 101, QtdaMax = 500, Valor = 4 },
                new QtdaGrupo() { CodigoGrupo = "C-1a", Efetivo = true, QtdaMin = 501, QtdaMax = 1000, Valor = 6 },
                new QtdaGrupo() { CodigoGrupo = "C-1a", Efetivo = true, QtdaMin = 1001, QtdaMax = 2500, Valor = 9 },
                new QtdaGrupo() { CodigoGrupo = "C-1a", Efetivo = true, QtdaMin = 2501, QtdaMax = 5000, Valor = 12 },
                new QtdaGrupo() { CodigoGrupo = "C-1a", Efetivo = true, QtdaMin = 5001, QtdaMax = 10000, Valor = 15 },
                new QtdaGrupo() { CodigoGrupo = "C-1a", Efetivo = false, QtdaMin = 0, QtdaMax = 19, Valor = 0 },
                new QtdaGrupo() { CodigoGrupo = "C-1a", Efetivo = false, QtdaMin = 20, QtdaMax = 50, Valor = 1 },
                new QtdaGrupo() { CodigoGrupo = "C-1a", Efetivo = false, QtdaMin = 51, QtdaMax = 300, Valor = 3 },
                new QtdaGrupo() { CodigoGrupo = "C-1a", Efetivo = false, QtdaMin = 301, QtdaMax = 500, Valor = 4 },
                new QtdaGrupo() { CodigoGrupo = "C-1a", Efetivo = false, QtdaMin = 501, QtdaMax = 1000, Valor = 5 },
                new QtdaGrupo() { CodigoGrupo = "C-1a", Efetivo = false, QtdaMin = 1001, QtdaMax = 2500, Valor = 8 },
                new QtdaGrupo() { CodigoGrupo = "C-1a", Efetivo = false, QtdaMin = 2501, QtdaMax = 5000, Valor = 9 },
                new QtdaGrupo() { CodigoGrupo = "C-1a", Efetivo = false, QtdaMin = 5001, QtdaMax = 10000, Valor = 12 },
                new QtdaGrupo() { CodigoGrupo = "C-2", Efetivo = true, QtdaMin = 0, QtdaMax = 19, Valor = 0 },
                new QtdaGrupo() { CodigoGrupo = "C-2", Efetivo = true, QtdaMin = 20, QtdaMax = 50, Valor = 1 },
                new QtdaGrupo() { CodigoGrupo = "C-2", Efetivo = true, QtdaMin = 51, QtdaMax = 100, Valor = 2 },
                new QtdaGrupo() { CodigoGrupo = "C-2", Efetivo = true, QtdaMin = 101, QtdaMax = 120, Valor = 3 },
                new QtdaGrupo() { CodigoGrupo = "C-2", Efetivo = true, QtdaMin = 121, QtdaMax = 300, Valor = 4 },
                new QtdaGrupo() { CodigoGrupo = "C-2", Efetivo = true, QtdaMin = 301, QtdaMax = 500, Valor = 5 },
                new QtdaGrupo() { CodigoGrupo = "C-2", Efetivo = true, QtdaMin = 501, QtdaMax = 1000, Valor = 6 },
                new QtdaGrupo() { CodigoGrupo = "C-2", Efetivo = true, QtdaMin = 1001, QtdaMax = 2500, Valor = 7 },
                new QtdaGrupo() { CodigoGrupo = "C-2", Efetivo = true, QtdaMin = 2501, QtdaMax = 5000, Valor = 10 },
                new QtdaGrupo() { CodigoGrupo = "C-2", Efetivo = true, QtdaMin = 5001, QtdaMax = 10000, Valor = 11 },
                new QtdaGrupo() { CodigoGrupo = "C-2", Efetivo = false, QtdaMin = 0, QtdaMax = 19, Valor = 0 },
                new QtdaGrupo() { CodigoGrupo = "C-2", Efetivo = false, QtdaMin = 20, QtdaMax = 50, Valor = 1 },
                new QtdaGrupo() { CodigoGrupo = "C-2", Efetivo = false, QtdaMin = 51, QtdaMax = 100, Valor = 2 },
                new QtdaGrupo() { CodigoGrupo = "C-2", Efetivo = false, QtdaMin = 101, QtdaMax = 140, Valor = 3 },
                new QtdaGrupo() { CodigoGrupo = "C-2", Efetivo = false, QtdaMin = 141, QtdaMax = 500, Valor = 4 },
                new QtdaGrupo() { CodigoGrupo = "C-2", Efetivo = false, QtdaMin = 501, QtdaMax = 1000, Valor = 5 },
                new QtdaGrupo() { CodigoGrupo = "C-2", Efetivo = false, QtdaMin = 1001, QtdaMax = 2500, Valor = 6 },
                new QtdaGrupo() { CodigoGrupo = "C-2", Efetivo = false, QtdaMin = 2501, QtdaMax = 5000, Valor = 7 },
                new QtdaGrupo() { CodigoGrupo = "C-2", Efetivo = false, QtdaMin = 5001, QtdaMax = 10000, Valor = 9 },
                new QtdaGrupo() { CodigoGrupo = "C-3", Efetivo = true, QtdaMin = 0, QtdaMax = 19, Valor = 0 },
                new QtdaGrupo() { CodigoGrupo = "C-3", Efetivo = true, QtdaMin = 20, QtdaMax = 50, Valor = 1 },
                new QtdaGrupo() { CodigoGrupo = "C-3", Efetivo = true, QtdaMin = 51, QtdaMax = 100, Valor = 2 },
                new QtdaGrupo() { CodigoGrupo = "C-3", Efetivo = true, QtdaMin = 101, QtdaMax = 140, Valor = 3 },
                new QtdaGrupo() { CodigoGrupo = "C-3", Efetivo = true, QtdaMin = 141, QtdaMax = 300, Valor = 4 },
                new QtdaGrupo() { CodigoGrupo = "C-3", Efetivo = true, QtdaMin = 301, QtdaMax = 500, Valor = 5 },
                new QtdaGrupo() { CodigoGrupo = "C-3", Efetivo = true, QtdaMin = 501, QtdaMax = 1000, Valor = 6 },
                new QtdaGrupo() { CodigoGrupo = "C-3", Efetivo = true, QtdaMin = 1001, QtdaMax = 2500, Valor = 7 },
                new QtdaGrupo() { CodigoGrupo = "C-3", Efetivo = true, QtdaMin = 2501, QtdaMax = 10000, Valor = 10 },
                new QtdaGrupo() { CodigoGrupo = "C-3", Efetivo = false, QtdaMin = 0, QtdaMax = 19, Valor = 0 },
                new QtdaGrupo() { CodigoGrupo = "C-3", Efetivo = false, QtdaMin = 20, QtdaMax = 50, Valor = 1 },
                new QtdaGrupo() { CodigoGrupo = "C-3", Efetivo = false, QtdaMin = 51, QtdaMax = 100, Valor = 2 },
                new QtdaGrupo() { CodigoGrupo = "C-3", Efetivo = false, QtdaMin = 101, QtdaMax = 140, Valor = 3 },
                new QtdaGrupo() { CodigoGrupo = "C-3", Efetivo = false, QtdaMin = 141, QtdaMax = 500, Valor = 4 },
                new QtdaGrupo() { CodigoGrupo = "C-3", Efetivo = false, QtdaMin = 501, QtdaMax = 1000, Valor = 5 },
                new QtdaGrupo() { CodigoGrupo = "C-3", Efetivo = false, QtdaMin = 1001, QtdaMax = 2500, Valor = 6 },
                new QtdaGrupo() { CodigoGrupo = "C-3", Efetivo = false, QtdaMin = 2501, QtdaMax = 10000, Valor = 8 },
                new QtdaGrupo() { CodigoGrupo = "C-3a", Efetivo = true, QtdaMin = 0, QtdaMax = 50, Valor = 0 },
                new QtdaGrupo() { CodigoGrupo = "C-3a", Efetivo = true, QtdaMin = 51, QtdaMax = 100, Valor = 1 },
                new QtdaGrupo() { CodigoGrupo = "C-3a", Efetivo = true, QtdaMin = 101, QtdaMax = 300, Valor = 2 },
                new QtdaGrupo() { CodigoGrupo = "C-3a", Efetivo = true, QtdaMin = 301, QtdaMax = 1000, Valor = 3 },
                new QtdaGrupo() { CodigoGrupo = "C-3a", Efetivo = true, QtdaMin = 1001, QtdaMax = 2500, Valor = 4 },
                new QtdaGrupo() { CodigoGrupo = "C-3a", Efetivo = true, QtdaMin = 2501, QtdaMax = 5000, Valor = 5 },
                new QtdaGrupo() { CodigoGrupo = "C-3a", Efetivo = true, QtdaMin = 5001, QtdaMax = 10000, Valor = 6 },
                new QtdaGrupo() { CodigoGrupo = "C-3a", Efetivo = false, QtdaMin = 0, QtdaMax = 50, Valor = 0 },
                new QtdaGrupo() { CodigoGrupo = "C-3a", Efetivo = false, QtdaMin = 51, QtdaMax = 100, Valor = 1 },
                new QtdaGrupo() { CodigoGrupo = "C-3a", Efetivo = false, QtdaMin = 101, QtdaMax = 300, Valor = 2 },
                new QtdaGrupo() { CodigoGrupo = "C-3a", Efetivo = false, QtdaMin = 301, QtdaMax = 2500, Valor = 3 },
                new QtdaGrupo() { CodigoGrupo = "C-3a", Efetivo = false, QtdaMin = 2501, QtdaMax = 5000, Valor = 4 },
                new QtdaGrupo() { CodigoGrupo = "C-3a", Efetivo = false, QtdaMin = 5001, QtdaMax = 10000, Valor = 5 },
                new QtdaGrupo() { CodigoGrupo = "C-4", Efetivo = true, QtdaMin = 0, QtdaMax = 29, Valor = 0 },
                new QtdaGrupo() { CodigoGrupo = "C-4", Efetivo = true, QtdaMin = 30, QtdaMax = 140, Valor = 1 },
                new QtdaGrupo() { CodigoGrupo = "C-4", Efetivo = true, QtdaMin = 141, QtdaMax = 1000, Valor = 2 },
                new QtdaGrupo() { CodigoGrupo = "C-4", Efetivo = true, QtdaMin = 1001, QtdaMax = 2500, Valor = 3 },
                new QtdaGrupo() { CodigoGrupo = "C-4", Efetivo = true, QtdaMin = 2501, QtdaMax = 5000, Valor = 5 },
                new QtdaGrupo() { CodigoGrupo = "C-4", Efetivo = true, QtdaMin = 5001, QtdaMax = 10000, Valor = 6 },
                new QtdaGrupo() { CodigoGrupo = "C-4", Efetivo = false, QtdaMin = 0, QtdaMax = 29, Valor = 0 },
                new QtdaGrupo() { CodigoGrupo = "C-4", Efetivo = false, QtdaMin = 30, QtdaMax = 140, Valor = 1 },
                new QtdaGrupo() { CodigoGrupo = "C-4", Efetivo = false, QtdaMin = 141, QtdaMax = 1000, Valor = 2 },
                new QtdaGrupo() { CodigoGrupo = "C-4", Efetivo = false, QtdaMin = 1001, QtdaMax = 2500, Valor = 3 },
                new QtdaGrupo() { CodigoGrupo = "C-4", Efetivo = false, QtdaMin = 2501, QtdaMax = 10000, Valor = 4 },
                new QtdaGrupo() { CodigoGrupo = "C-5", Efetivo = true, QtdaMin = 0, QtdaMax = 19, Valor = 0 },
                new QtdaGrupo() { CodigoGrupo = "C-5", Efetivo = true, QtdaMin = 20, QtdaMax = 50, Valor = 1 },
                new QtdaGrupo() { CodigoGrupo = "C-5", Efetivo = true, QtdaMin = 51, QtdaMax = 80, Valor = 2 },
                new QtdaGrupo() { CodigoGrupo = "C-5", Efetivo = true, QtdaMin = 81, QtdaMax = 120, Valor = 3 },
                new QtdaGrupo() { CodigoGrupo = "C-5", Efetivo = true, QtdaMin = 121, QtdaMax = 500, Valor = 4 },
                new QtdaGrupo() { CodigoGrupo = "C-5", Efetivo = true, QtdaMin = 501, QtdaMax = 1000, Valor = 6 },
                new QtdaGrupo() { CodigoGrupo = "C-5", Efetivo = true, QtdaMin = 1001, QtdaMax = 5000, Valor = 9 },
                new QtdaGrupo() { CodigoGrupo = "C-5", Efetivo = true, QtdaMin = 5001, QtdaMax = 10000, Valor = 11 },
                new QtdaGrupo() { CodigoGrupo = "C-5", Efetivo = false, QtdaMin = 0, QtdaMax = 19, Valor = 0 },
                new QtdaGrupo() { CodigoGrupo = "C-5", Efetivo = false, QtdaMin = 20, QtdaMax = 50, Valor = 1 },
                new QtdaGrupo() { CodigoGrupo = "C-5", Efetivo = false, QtdaMin = 51, QtdaMax = 80, Valor = 2 },
                new QtdaGrupo() { CodigoGrupo = "C-5", Efetivo = false, QtdaMin = 81, QtdaMax = 140, Valor = 3 },
                new QtdaGrupo() { CodigoGrupo = "C-5", Efetivo = false, QtdaMin = 141, QtdaMax = 500, Valor = 4 },
                new QtdaGrupo() { CodigoGrupo = "C-5", Efetivo = false, QtdaMin = 501, QtdaMax = 1000, Valor = 5 },
                new QtdaGrupo() { CodigoGrupo = "C-5", Efetivo = false, QtdaMin = 1001, QtdaMax = 5000, Valor = 7 },
                new QtdaGrupo() { CodigoGrupo = "C-5", Efetivo = false, QtdaMin = 5001, QtdaMax = 10000, Valor = 9 },
                new QtdaGrupo() { CodigoGrupo = "C-5a", Efetivo = true, QtdaMin = 0, QtdaMax = 50, Valor = 0 },
                new QtdaGrupo() { CodigoGrupo = "C-5a", Efetivo = true, QtdaMin = 51, QtdaMax = 100, Valor = 1 },
                new QtdaGrupo() { CodigoGrupo = "C-5a", Efetivo = true, QtdaMin = 101, QtdaMax = 300, Valor = 2 },
                new QtdaGrupo() { CodigoGrupo = "C-5a", Efetivo = true, QtdaMin = 301, QtdaMax = 1000, Valor = 3 },
                new QtdaGrupo() { CodigoGrupo = "C-5a", Efetivo = true, QtdaMin = 1001, QtdaMax = 2500, Valor = 4 },
                new QtdaGrupo() { CodigoGrupo = "C-5a", Efetivo = true, QtdaMin = 2501, QtdaMax = 5000, Valor = 6 },
                new QtdaGrupo() { CodigoGrupo = "C-5a", Efetivo = true, QtdaMin = 5001, QtdaMax = 10000, Valor = 7 },
                new QtdaGrupo() { CodigoGrupo = "C-5a", Efetivo = false, QtdaMin = 0, QtdaMax = 50, Valor = 0 },
                new QtdaGrupo() { CodigoGrupo = "C-5a", Efetivo = false, QtdaMin = 51, QtdaMax = 100, Valor = 1 },
                new QtdaGrupo() { CodigoGrupo = "C-5a", Efetivo = false, QtdaMin = 101, QtdaMax = 300, Valor = 2 },
                new QtdaGrupo() { CodigoGrupo = "C-5a", Efetivo = false, QtdaMin = 301, QtdaMax = 2500, Valor = 3 },
                new QtdaGrupo() { CodigoGrupo = "C-5a", Efetivo = false, QtdaMin = 2501, QtdaMax = 5000, Valor = 4 },
                new QtdaGrupo() { CodigoGrupo = "C-5a", Efetivo = false, QtdaMin = 5001, QtdaMax = 10000, Valor = 5 },
                new QtdaGrupo() { CodigoGrupo = "C-6", Efetivo = true, QtdaMin = 0, QtdaMax = 19, Valor = 0 },
                new QtdaGrupo() { CodigoGrupo = "C-6", Efetivo = true, QtdaMin = 20, QtdaMax = 50, Valor = 1 },
                new QtdaGrupo() { CodigoGrupo = "C-6", Efetivo = true, QtdaMin = 51, QtdaMax = 80, Valor = 2 },
                new QtdaGrupo() { CodigoGrupo = "C-6", Efetivo = true, QtdaMin = 81, QtdaMax = 120, Valor = 3 },
                new QtdaGrupo() { CodigoGrupo = "C-6", Efetivo = true, QtdaMin = 121, QtdaMax = 140, Valor = 4 },
                new QtdaGrupo() { CodigoGrupo = "C-6", Efetivo = true, QtdaMin = 141, QtdaMax = 500, Valor = 5 },
                new QtdaGrupo() { CodigoGrupo = "C-6", Efetivo = true, QtdaMin = 501, QtdaMax = 1000, Valor = 6 },
                new QtdaGrupo() { CodigoGrupo = "C-6", Efetivo = true, QtdaMin = 1001, QtdaMax = 2500, Valor = 8 },
                new QtdaGrupo() { CodigoGrupo = "C-6", Efetivo = true, QtdaMin = 2501, QtdaMax = 5000, Valor = 10 },
                new QtdaGrupo() { CodigoGrupo = "C-6", Efetivo = true, QtdaMin = 5001, QtdaMax = 10000, Valor = 12 },
                new QtdaGrupo() { CodigoGrupo = "C-6", Efetivo = false, QtdaMin = 0, QtdaMax = 19, Valor = 0 },
                new QtdaGrupo() { CodigoGrupo = "C-6", Efetivo = false, QtdaMin = 20, QtdaMax = 50, Valor = 1 },
                new QtdaGrupo() { CodigoGrupo = "C-6", Efetivo = false, QtdaMin = 51, QtdaMax = 80, Valor = 2 },
                new QtdaGrupo() { CodigoGrupo = "C-6", Efetivo = false, QtdaMin = 81, QtdaMax = 140, Valor = 3 },
                new QtdaGrupo() { CodigoGrupo = "C-6", Efetivo = false, QtdaMin = 141, QtdaMax = 1000, Valor = 4 },
                new QtdaGrupo() { CodigoGrupo = "C-6", Efetivo = false, QtdaMin = 1001, QtdaMax = 2500, Valor = 6 },
                new QtdaGrupo() { CodigoGrupo = "C-6", Efetivo = false, QtdaMin = 2501, QtdaMax = 5000, Valor = 8 },
                new QtdaGrupo() { CodigoGrupo = "C-6", Efetivo = false, QtdaMin = 5001, QtdaMax = 10000, Valor = 10 },
                new QtdaGrupo() { CodigoGrupo = "C-7", Efetivo = true, QtdaMin = 0, QtdaMax = 50, Valor = 0 },
                new QtdaGrupo() { CodigoGrupo = "C-7", Efetivo = true, QtdaMin = 51, QtdaMax = 100, Valor = 1 },
                new QtdaGrupo() { CodigoGrupo = "C-7", Efetivo = true, QtdaMin = 101, QtdaMax = 500, Valor = 2 },
                new QtdaGrupo() { CodigoGrupo = "C-7", Efetivo = true, QtdaMin = 501, QtdaMax = 1000, Valor = 3 },
                new QtdaGrupo() { CodigoGrupo = "C-7", Efetivo = true, QtdaMin = 1001, QtdaMax = 2500, Valor = 4 },
                new QtdaGrupo() { CodigoGrupo = "C-7", Efetivo = true, QtdaMin = 2501, QtdaMax = 5000, Valor = 5 },
                new QtdaGrupo() { CodigoGrupo = "C-7", Efetivo = true, QtdaMin = 5001, QtdaMax = 10000, Valor = 6 },
                new QtdaGrupo() { CodigoGrupo = "C-7", Efetivo = false, QtdaMin = 0, QtdaMax = 50, Valor = 0 },
                new QtdaGrupo() { CodigoGrupo = "C-7", Efetivo = false, QtdaMin = 51, QtdaMax = 100, Valor = 1 },
                new QtdaGrupo() { CodigoGrupo = "C-7", Efetivo = false, QtdaMin = 101, QtdaMax = 500, Valor = 2 },
                new QtdaGrupo() { CodigoGrupo = "C-7", Efetivo = false, QtdaMin = 501, QtdaMax = 2500, Valor = 3 },
                new QtdaGrupo() { CodigoGrupo = "C-7", Efetivo = false, QtdaMin = 2501, QtdaMax = 10000, Valor = 4 },
                new QtdaGrupo() { CodigoGrupo = "C-7a", Efetivo = true, QtdaMin = 0, QtdaMax = 19, Valor = 0 },
                new QtdaGrupo() { CodigoGrupo = "C-7a", Efetivo = true, QtdaMin = 20, QtdaMax = 50, Valor = 1 },
                new QtdaGrupo() { CodigoGrupo = "C-7a", Efetivo = true, QtdaMin = 51, QtdaMax = 100, Valor = 2 },
                new QtdaGrupo() { CodigoGrupo = "C-7a", Efetivo = true, QtdaMin = 101, QtdaMax = 140, Valor = 3 },
                new QtdaGrupo() { CodigoGrupo = "C-7a", Efetivo = true, QtdaMin = 141, QtdaMax = 300, Valor = 4 },
                new QtdaGrupo() { CodigoGrupo = "C-7a", Efetivo = true, QtdaMin = 301, QtdaMax = 500, Valor = 5 },
                new QtdaGrupo() { CodigoGrupo = "C-7a", Efetivo = true, QtdaMin = 501, QtdaMax = 1000, Valor = 6 },
                new QtdaGrupo() { CodigoGrupo = "C-7a", Efetivo = true, QtdaMin = 1001, QtdaMax = 2500, Valor = 8 },
                new QtdaGrupo() { CodigoGrupo = "C-7a", Efetivo = true, QtdaMin = 2501, QtdaMax = 5000, Valor = 9 },
                new QtdaGrupo() { CodigoGrupo = "C-7a", Efetivo = true, QtdaMin = 5001, QtdaMax = 10000, Valor = 10 },
                new QtdaGrupo() { CodigoGrupo = "C-7a", Efetivo = false, QtdaMin = 0, QtdaMax = 19, Valor = 0 },
                new QtdaGrupo() { CodigoGrupo = "C-7a", Efetivo = false, QtdaMin = 20, QtdaMax = 50, Valor = 1 },
                new QtdaGrupo() { CodigoGrupo = "C-7a", Efetivo = false, QtdaMin = 51, QtdaMax = 100, Valor = 2 },
                new QtdaGrupo() { CodigoGrupo = "C-7a", Efetivo = false, QtdaMin = 101, QtdaMax = 300, Valor = 3 },
                new QtdaGrupo() { CodigoGrupo = "C-7a", Efetivo = false, QtdaMin = 301, QtdaMax = 500, Valor = 4 },
                new QtdaGrupo() { CodigoGrupo = "C-7a", Efetivo = false, QtdaMin = 501, QtdaMax = 1000, Valor = 5 },
                new QtdaGrupo() { CodigoGrupo = "C-7a", Efetivo = false, QtdaMin = 1001, QtdaMax = 2500, Valor = 7 },
                new QtdaGrupo() { CodigoGrupo = "C-7a", Efetivo = false, QtdaMin = 2501, QtdaMax = 10000, Valor = 8 },
                new QtdaGrupo() { CodigoGrupo = "C-8", Efetivo = true, QtdaMin = 0, QtdaMax = 19, Valor = 0 },
                new QtdaGrupo() { CodigoGrupo = "C-8", Efetivo = true, QtdaMin = 20, QtdaMax = 50, Valor = 1 },
                new QtdaGrupo() { CodigoGrupo = "C-8", Efetivo = true, QtdaMin = 51, QtdaMax = 100, Valor = 2 },
                new QtdaGrupo() { CodigoGrupo = "C-8", Efetivo = true, QtdaMin = 101, QtdaMax = 140, Valor = 3 },
                new QtdaGrupo() { CodigoGrupo = "C-8", Efetivo = true, QtdaMin = 141, QtdaMax = 300, Valor = 4 },
                new QtdaGrupo() { CodigoGrupo = "C-8", Efetivo = true, QtdaMin = 301, QtdaMax = 500, Valor = 5 },
                new QtdaGrupo() { CodigoGrupo = "C-8", Efetivo = true, QtdaMin = 501, QtdaMax = 1000, Valor = 6 },
                new QtdaGrupo() { CodigoGrupo = "C-8", Efetivo = true, QtdaMin = 1001, QtdaMax = 2500, Valor = 7 },
                new QtdaGrupo() { CodigoGrupo = "C-8", Efetivo = true, QtdaMin = 2501, QtdaMax = 5000, Valor = 8 },
                new QtdaGrupo() { CodigoGrupo = "C-8", Efetivo = true, QtdaMin = 5001, QtdaMax = 10000, Valor = 10 },
                new QtdaGrupo() { CodigoGrupo = "C-8", Efetivo = false, QtdaMin = 0, QtdaMax = 19, Valor = 0 },
                new QtdaGrupo() { CodigoGrupo = "C-8", Efetivo = false, QtdaMin = 20, QtdaMax = 50, Valor = 1 },
                new QtdaGrupo() { CodigoGrupo = "C-8", Efetivo = false, QtdaMin = 51, QtdaMax = 100, Valor = 2 },
                new QtdaGrupo() { CodigoGrupo = "C-8", Efetivo = false, QtdaMin = 101, QtdaMax = 300, Valor = 3 },
                new QtdaGrupo() { CodigoGrupo = "C-8", Efetivo = false, QtdaMin = 301, QtdaMax = 1000, Valor = 4 },
                new QtdaGrupo() { CodigoGrupo = "C-8", Efetivo = false, QtdaMin = 1001, QtdaMax = 2500, Valor = 5 },
                new QtdaGrupo() { CodigoGrupo = "C-8", Efetivo = false, QtdaMin = 2501, QtdaMax = 5000, Valor = 6 },
                new QtdaGrupo() { CodigoGrupo = "C-8", Efetivo = false, QtdaMin = 5001, QtdaMax = 10000, Valor = 8 },
                new QtdaGrupo() { CodigoGrupo = "C-9", Efetivo = true, QtdaMin = 0, QtdaMax = 50, Valor = 0 },
                new QtdaGrupo() { CodigoGrupo = "C-9", Efetivo = true, QtdaMin = 51, QtdaMax = 120, Valor = 1 },
                new QtdaGrupo() { CodigoGrupo = "C-9", Efetivo = true, QtdaMin = 121, QtdaMax = 500, Valor = 2 },
                new QtdaGrupo() { CodigoGrupo = "C-9", Efetivo = true, QtdaMin = 501, QtdaMax = 1000, Valor = 3 },
                new QtdaGrupo() { CodigoGrupo = "C-9", Efetivo = true, QtdaMin = 1001, QtdaMax = 2500, Valor = 5 },
                new QtdaGrupo() { CodigoGrupo = "C-9", Efetivo = true, QtdaMin = 2501, QtdaMax = 5000, Valor = 6 },
                new QtdaGrupo() { CodigoGrupo = "C-9", Efetivo = true, QtdaMin = 5001, QtdaMax = 10000, Valor = 7 },
                new QtdaGrupo() { CodigoGrupo = "C-9", Efetivo = false, QtdaMin = 0, QtdaMax = 50, Valor = 0 },
                new QtdaGrupo() { CodigoGrupo = "C-9", Efetivo = false, QtdaMin = 51, QtdaMax = 120, Valor = 1 },
                new QtdaGrupo() { CodigoGrupo = "C-9", Efetivo = false, QtdaMin = 121, QtdaMax = 500, Valor = 2 },
                new QtdaGrupo() { CodigoGrupo = "C-9", Efetivo = false, QtdaMin = 501, QtdaMax = 1000, Valor = 3 },
                new QtdaGrupo() { CodigoGrupo = "C-9", Efetivo = false, QtdaMin = 1001, QtdaMax = 5000, Valor = 4 },
                new QtdaGrupo() { CodigoGrupo = "C-9", Efetivo = false, QtdaMin = 5001, QtdaMax = 10000, Valor = 5 },
                new QtdaGrupo() { CodigoGrupo = "C-10", Efetivo = true, QtdaMin = 0, QtdaMax = 19, Valor = 0 },
                new QtdaGrupo() { CodigoGrupo = "C-10", Efetivo = true, QtdaMin = 20, QtdaMax = 50, Valor = 1 },
                new QtdaGrupo() { CodigoGrupo = "C-10", Efetivo = true, QtdaMin = 51, QtdaMax = 100, Valor = 2 },
                new QtdaGrupo() { CodigoGrupo = "C-10", Efetivo = true, QtdaMin = 101, QtdaMax = 140, Valor = 3 },
                new QtdaGrupo() { CodigoGrupo = "C-10", Efetivo = true, QtdaMin = 141, QtdaMax = 500, Valor = 4 },
                new QtdaGrupo() { CodigoGrupo = "C-10", Efetivo = true, QtdaMin = 501, QtdaMax = 1000, Valor = 5 },
                new QtdaGrupo() { CodigoGrupo = "C-10", Efetivo = true, QtdaMin = 1001, QtdaMax = 2500, Valor = 8 },
                new QtdaGrupo() { CodigoGrupo = "C-10", Efetivo = true, QtdaMin = 2501, QtdaMax = 5000, Valor = 9 },
                new QtdaGrupo() { CodigoGrupo = "C-10", Efetivo = true, QtdaMin = 5001, QtdaMax = 10000, Valor = 10 },
                new QtdaGrupo() { CodigoGrupo = "C-10", Efetivo = false, QtdaMin = 0, QtdaMax = 19, Valor = 0 },
                new QtdaGrupo() { CodigoGrupo = "C-10", Efetivo = false, QtdaMin = 20, QtdaMax = 50, Valor = 1 },
                new QtdaGrupo() { CodigoGrupo = "C-10", Efetivo = false, QtdaMin = 51, QtdaMax = 100, Valor = 2 },
                new QtdaGrupo() { CodigoGrupo = "C-10", Efetivo = false, QtdaMin = 101, QtdaMax = 300, Valor = 3 },
                new QtdaGrupo() { CodigoGrupo = "C-10", Efetivo = false, QtdaMin = 301, QtdaMax = 1000, Valor = 4 },
                new QtdaGrupo() { CodigoGrupo = "C-10", Efetivo = false, QtdaMin = 1001, QtdaMax = 2500, Valor = 6 },
                new QtdaGrupo() { CodigoGrupo = "C-10", Efetivo = false, QtdaMin = 2501, QtdaMax = 5000, Valor = 7 },
                new QtdaGrupo() { CodigoGrupo = "C-10", Efetivo = false, QtdaMin = 5001, QtdaMax = 10000, Valor = 8 },
                new QtdaGrupo() { CodigoGrupo = "C-11", Efetivo = true, QtdaMin = 0, QtdaMax = 19, Valor = 0 },
                new QtdaGrupo() { CodigoGrupo = "C-11", Efetivo = true, QtdaMin = 20, QtdaMax = 50, Valor = 1 },
                new QtdaGrupo() { CodigoGrupo = "C-11", Efetivo = true, QtdaMin = 51, QtdaMax = 80, Valor = 2 },
                new QtdaGrupo() { CodigoGrupo = "C-11", Efetivo = true, QtdaMin = 81, QtdaMax = 120, Valor = 3 },
                new QtdaGrupo() { CodigoGrupo = "C-11", Efetivo = true, QtdaMin = 121, QtdaMax = 300, Valor = 4 },
                new QtdaGrupo() { CodigoGrupo = "C-11", Efetivo = true, QtdaMin = 301, QtdaMax = 500, Valor = 5 },
                new QtdaGrupo() { CodigoGrupo = "C-11", Efetivo = true, QtdaMin = 501, QtdaMax = 1000, Valor = 6 },
                new QtdaGrupo() { CodigoGrupo = "C-11", Efetivo = true, QtdaMin = 1001, QtdaMax = 2500, Valor = 9 },
                new QtdaGrupo() { CodigoGrupo = "C-11", Efetivo = true, QtdaMin = 2501, QtdaMax = 5000, Valor = 10 },
                new QtdaGrupo() { CodigoGrupo = "C-11", Efetivo = true, QtdaMin = 5001, QtdaMax = 10000, Valor = 12 },
                new QtdaGrupo() { CodigoGrupo = "C-11", Efetivo = false, QtdaMin = 0, QtdaMax = 19, Valor = 0 },
                new QtdaGrupo() { CodigoGrupo = "C-11", Efetivo = false, QtdaMin = 20, QtdaMax = 50, Valor = 1 },
                new QtdaGrupo() { CodigoGrupo = "C-11", Efetivo = false, QtdaMin = 51, QtdaMax = 80, Valor = 2 },
                new QtdaGrupo() { CodigoGrupo = "C-11", Efetivo = false, QtdaMin = 81, QtdaMax = 300, Valor = 3 },
                new QtdaGrupo() { CodigoGrupo = "C-11", Efetivo = false, QtdaMin = 301, QtdaMax = 1000, Valor = 4 },
                new QtdaGrupo() { CodigoGrupo = "C-11", Efetivo = false, QtdaMin = 1001, QtdaMax = 2500, Valor = 7 },
                new QtdaGrupo() { CodigoGrupo = "C-11", Efetivo = false, QtdaMin = 2501, QtdaMax = 5000, Valor = 8 },
                new QtdaGrupo() { CodigoGrupo = "C-11", Efetivo = false, QtdaMin = 5001, QtdaMax = 10000, Valor = 10 },
                new QtdaGrupo() { CodigoGrupo = "C-12", Efetivo = true, QtdaMin = 0, QtdaMax = 19, Valor = 0 },
                new QtdaGrupo() { CodigoGrupo = "C-12", Efetivo = true, QtdaMin = 20, QtdaMax = 50, Valor = 1 },
                new QtdaGrupo() { CodigoGrupo = "C-12", Efetivo = true, QtdaMin = 51, QtdaMax = 80, Valor = 2 },
                new QtdaGrupo() { CodigoGrupo = "C-12", Efetivo = true, QtdaMin = 81, QtdaMax = 120, Valor = 3 },
                new QtdaGrupo() { CodigoGrupo = "C-12", Efetivo = true, QtdaMin = 121, QtdaMax = 300, Valor = 4 },
                new QtdaGrupo() { CodigoGrupo = "C-12", Efetivo = true, QtdaMin = 301, QtdaMax = 500, Valor = 5 },
                new QtdaGrupo() { CodigoGrupo = "C-12", Efetivo = true, QtdaMin = 501, QtdaMax = 1000, Valor = 7 },
                new QtdaGrupo() { CodigoGrupo = "C-12", Efetivo = true, QtdaMin = 1001, QtdaMax = 2500, Valor = 8 },
                new QtdaGrupo() { CodigoGrupo = "C-12", Efetivo = true, QtdaMin = 2501, QtdaMax = 5000, Valor = 9 },
                new QtdaGrupo() { CodigoGrupo = "C-12", Efetivo = true, QtdaMin = 5001, QtdaMax = 10000, Valor = 10 },
                new QtdaGrupo() { CodigoGrupo = "C-12", Efetivo = false, QtdaMin = 0, QtdaMax = 19, Valor = 0 },
                new QtdaGrupo() { CodigoGrupo = "C-12", Efetivo = false, QtdaMin = 20, QtdaMax = 50, Valor = 1 },
                new QtdaGrupo() { CodigoGrupo = "C-12", Efetivo = false, QtdaMin = 51, QtdaMax = 80, Valor = 2 },
                new QtdaGrupo() { CodigoGrupo = "C-12", Efetivo = false, QtdaMin = 81, QtdaMax = 300, Valor = 3 },
                new QtdaGrupo() { CodigoGrupo = "C-12", Efetivo = false, QtdaMin = 301, QtdaMax = 500, Valor = 4 },
                new QtdaGrupo() { CodigoGrupo = "C-12", Efetivo = false, QtdaMin = 501, QtdaMax = 2500, Valor = 6 },
                new QtdaGrupo() { CodigoGrupo = "C-12", Efetivo = false, QtdaMin = 2501, QtdaMax = 5000, Valor = 7 },
                new QtdaGrupo() { CodigoGrupo = "C-12", Efetivo = false, QtdaMin = 5001, QtdaMax = 10000, Valor = 8 },
                new QtdaGrupo() { CodigoGrupo = "C-13", Efetivo = true, QtdaMin = 0, QtdaMax = 19, Valor = 0 },
                new QtdaGrupo() { CodigoGrupo = "C-13", Efetivo = true, QtdaMin = 20, QtdaMax = 50, Valor = 1 },
                new QtdaGrupo() { CodigoGrupo = "C-13", Efetivo = true, QtdaMin = 51, QtdaMax = 140, Valor = 3 },
                new QtdaGrupo() { CodigoGrupo = "C-13", Efetivo = true, QtdaMin = 141, QtdaMax = 300, Valor = 4 },
                new QtdaGrupo() { CodigoGrupo = "C-13", Efetivo = true, QtdaMin = 301, QtdaMax = 500, Valor = 5 },
                new QtdaGrupo() { CodigoGrupo = "C-13", Efetivo = true, QtdaMin = 501, QtdaMax = 1000, Valor = 6 },
                new QtdaGrupo() { CodigoGrupo = "C-13", Efetivo = true, QtdaMin = 1001, QtdaMax = 2500, Valor = 9 },
                new QtdaGrupo() { CodigoGrupo = "C-13", Efetivo = true, QtdaMin = 2501, QtdaMax = 5000, Valor = 11 },
                new QtdaGrupo() { CodigoGrupo = "C-13", Efetivo = true, QtdaMin = 5001, QtdaMax = 10000, Valor = 13 },
                new QtdaGrupo() { CodigoGrupo = "C-13", Efetivo = false, QtdaMin = 0, QtdaMax = 19, Valor = 0 },
                new QtdaGrupo() { CodigoGrupo = "C-13", Efetivo = false, QtdaMin = 20, QtdaMax = 50, Valor = 1 },
                new QtdaGrupo() { CodigoGrupo = "C-13", Efetivo = false, QtdaMin = 51, QtdaMax = 300, Valor = 3 },
                new QtdaGrupo() { CodigoGrupo = "C-13", Efetivo = false, QtdaMin = 301, QtdaMax = 500, Valor = 4 },
                new QtdaGrupo() { CodigoGrupo = "C-13", Efetivo = false, QtdaMin = 501, QtdaMax = 1000, Valor = 5 },
                new QtdaGrupo() { CodigoGrupo = "C-13", Efetivo = false, QtdaMin = 1001, QtdaMax = 2500, Valor = 7 },
                new QtdaGrupo() { CodigoGrupo = "C-13", Efetivo = false, QtdaMin = 2501, QtdaMax = 5000, Valor = 8 },
                new QtdaGrupo() { CodigoGrupo = "C-13", Efetivo = false, QtdaMin = 5001, QtdaMax = 10000, Valor = 10 },
                new QtdaGrupo() { CodigoGrupo = "C-14", Efetivo = true, QtdaMin = 0, QtdaMax = 19, Valor = 0 },
                new QtdaGrupo() { CodigoGrupo = "C-14", Efetivo = true, QtdaMin = 20, QtdaMax = 50, Valor = 1 },
                new QtdaGrupo() { CodigoGrupo = "C-14", Efetivo = true, QtdaMin = 51, QtdaMax = 100, Valor = 2 },
                new QtdaGrupo() { CodigoGrupo = "C-14", Efetivo = true, QtdaMin = 101, QtdaMax = 120, Valor = 3 },
                new QtdaGrupo() { CodigoGrupo = "C-14", Efetivo = true, QtdaMin = 121, QtdaMax = 300, Valor = 4 },
                new QtdaGrupo() { CodigoGrupo = "C-14", Efetivo = true, QtdaMin = 301, QtdaMax = 500, Valor = 5 },
                new QtdaGrupo() { CodigoGrupo = "C-14", Efetivo = true, QtdaMin = 501, QtdaMax = 1000, Valor = 6 },
                new QtdaGrupo() { CodigoGrupo = "C-14", Efetivo = true, QtdaMin = 1001, QtdaMax = 2500, Valor = 9 },
                new QtdaGrupo() { CodigoGrupo = "C-14", Efetivo = true, QtdaMin = 2501, QtdaMax = 10000, Valor = 11 },
                new QtdaGrupo() { CodigoGrupo = "C-14", Efetivo = false, QtdaMin = 0, QtdaMax = 19, Valor = 0 },
                new QtdaGrupo() { CodigoGrupo = "C-14", Efetivo = false, QtdaMin = 20, QtdaMax = 50, Valor = 1 },
                new QtdaGrupo() { CodigoGrupo = "C-14", Efetivo = false, QtdaMin = 51, QtdaMax = 100, Valor = 2 },
                new QtdaGrupo() { CodigoGrupo = "C-14", Efetivo = false, QtdaMin = 101, QtdaMax = 140, Valor = 3 },
                new QtdaGrupo() { CodigoGrupo = "C-14", Efetivo = false, QtdaMin = 141, QtdaMax = 500, Valor = 4 },
                new QtdaGrupo() { CodigoGrupo = "C-14", Efetivo = false, QtdaMin = 501, QtdaMax = 1000, Valor = 5 },
                new QtdaGrupo() { CodigoGrupo = "C-14", Efetivo = false, QtdaMin = 1001, QtdaMax = 2500, Valor = 7 },
                new QtdaGrupo() { CodigoGrupo = "C-14", Efetivo = false, QtdaMin = 2501, QtdaMax = 10000, Valor = 9 },
                new QtdaGrupo() { CodigoGrupo = "C-14a", Efetivo = true, QtdaMin = 0, QtdaMax = 50, Valor = 0 },
                new QtdaGrupo() { CodigoGrupo = "C-14a", Efetivo = true, QtdaMin = 51, QtdaMax = 100, Valor = 1 },
                new QtdaGrupo() { CodigoGrupo = "C-14a", Efetivo = true, QtdaMin = 101, QtdaMax = 300, Valor = 2 },
                new QtdaGrupo() { CodigoGrupo = "C-14a", Efetivo = true, QtdaMin = 301, QtdaMax = 1000, Valor = 3 },
                new QtdaGrupo() { CodigoGrupo = "C-14a", Efetivo = true, QtdaMin = 1001, QtdaMax = 2500, Valor = 4 },
                new QtdaGrupo() { CodigoGrupo = "C-14a", Efetivo = true, QtdaMin = 2501, QtdaMax = 5000, Valor = 5 },
                new QtdaGrupo() { CodigoGrupo = "C-14a", Efetivo = true, QtdaMin = 5001, QtdaMax = 10000, Valor = 6 },
                new QtdaGrupo() { CodigoGrupo = "C-14a", Efetivo = false, QtdaMin = 0, QtdaMax = 50, Valor = 0 },
                new QtdaGrupo() { CodigoGrupo = "C-14a", Efetivo = false, QtdaMin = 51, QtdaMax = 100, Valor = 1 },
                new QtdaGrupo() { CodigoGrupo = "C-14a", Efetivo = false, QtdaMin = 101, QtdaMax = 300, Valor = 2 },
                new QtdaGrupo() { CodigoGrupo = "C-14a", Efetivo = false, QtdaMin = 301, QtdaMax = 2500, Valor = 3 },
                new QtdaGrupo() { CodigoGrupo = "C-14a", Efetivo = false, QtdaMin = 2501, QtdaMax = 10000, Valor = 4 },
                new QtdaGrupo() { CodigoGrupo = "C-15", Efetivo = true, QtdaMin = 0, QtdaMax = 19, Valor = 0 },
                new QtdaGrupo() { CodigoGrupo = "C-15", Efetivo = true, QtdaMin = 20, QtdaMax = 50, Valor = 1 },
                new QtdaGrupo() { CodigoGrupo = "C-15", Efetivo = true, QtdaMin = 51, QtdaMax = 100, Valor = 3 },
                new QtdaGrupo() { CodigoGrupo = "C-15", Efetivo = true, QtdaMin = 101, QtdaMax = 300, Valor = 4 },
                new QtdaGrupo() { CodigoGrupo = "C-15", Efetivo = true, QtdaMin = 301, QtdaMax = 500, Valor = 5 },
                new QtdaGrupo() { CodigoGrupo = "C-15", Efetivo = true, QtdaMin = 501, QtdaMax = 1000, Valor = 6 },
                new QtdaGrupo() { CodigoGrupo = "C-15", Efetivo = true, QtdaMin = 1001, QtdaMax = 2500, Valor = 8 },
                new QtdaGrupo() { CodigoGrupo = "C-15", Efetivo = true, QtdaMin = 2501, QtdaMax = 5000, Valor = 10 },
                new QtdaGrupo() { CodigoGrupo = "C-15", Efetivo = true, QtdaMin = 5001, QtdaMax = 10000, Valor = 12 },
                new QtdaGrupo() { CodigoGrupo = "C-15", Efetivo = false, QtdaMin = 0, QtdaMax = 19, Valor = 0 },
                new QtdaGrupo() { CodigoGrupo = "C-15", Efetivo = false, QtdaMin = 20, QtdaMax = 50, Valor = 1 },
                new QtdaGrupo() { CodigoGrupo = "C-15", Efetivo = false, QtdaMin = 51, QtdaMax = 300, Valor = 3 },
                new QtdaGrupo() { CodigoGrupo = "C-15", Efetivo = false, QtdaMin = 301, QtdaMax = 1000, Valor = 4 },
                new QtdaGrupo() { CodigoGrupo = "C-15", Efetivo = false, QtdaMin = 1001, QtdaMax = 2500, Valor = 6 },
                new QtdaGrupo() { CodigoGrupo = "C-15", Efetivo = false, QtdaMin = 2501, QtdaMax = 5000, Valor = 8 },
                new QtdaGrupo() { CodigoGrupo = "C-15", Efetivo = false, QtdaMin = 5001, QtdaMax = 10000, Valor = 10 },
                new QtdaGrupo() { CodigoGrupo = "C-16", Efetivo = true, QtdaMin = 0, QtdaMax = 19, Valor = 0 },
                new QtdaGrupo() { CodigoGrupo = "C-16", Efetivo = true, QtdaMin = 20, QtdaMax = 50, Valor = 1 },
                new QtdaGrupo() { CodigoGrupo = "C-16", Efetivo = true, QtdaMin = 51, QtdaMax = 80, Valor = 2 },
                new QtdaGrupo() { CodigoGrupo = "C-16", Efetivo = true, QtdaMin = 81, QtdaMax = 140, Valor = 3 },
                new QtdaGrupo() { CodigoGrupo = "C-16", Efetivo = true, QtdaMin = 141, QtdaMax = 300, Valor = 4 },
                new QtdaGrupo() { CodigoGrupo = "C-16", Efetivo = true, QtdaMin = 301, QtdaMax = 500, Valor = 5 },
                new QtdaGrupo() { CodigoGrupo = "C-16", Efetivo = true, QtdaMin = 501, QtdaMax = 1000, Valor = 6 },
                new QtdaGrupo() { CodigoGrupo = "C-16", Efetivo = true, QtdaMin = 1001, QtdaMax = 2500, Valor = 8 },
                new QtdaGrupo() { CodigoGrupo = "C-16", Efetivo = true, QtdaMin = 2501, QtdaMax = 5000, Valor = 10 },
                new QtdaGrupo() { CodigoGrupo = "C-16", Efetivo = true, QtdaMin = 5001, QtdaMax = 10000, Valor = 12 },
                new QtdaGrupo() { CodigoGrupo = "C-16", Efetivo = false, QtdaMin = 0, QtdaMax = 19, Valor = 0 },
                new QtdaGrupo() { CodigoGrupo = "C-16", Efetivo = false, QtdaMin = 20, QtdaMax = 50, Valor = 1 },
                new QtdaGrupo() { CodigoGrupo = "C-16", Efetivo = false, QtdaMin = 51, QtdaMax = 80, Valor = 2 },
                new QtdaGrupo() { CodigoGrupo = "C-16", Efetivo = false, QtdaMin = 81, QtdaMax = 300, Valor = 3 },
                new QtdaGrupo() { CodigoGrupo = "C-16", Efetivo = false, QtdaMin = 301, QtdaMax = 1000, Valor = 4 },
                new QtdaGrupo() { CodigoGrupo = "C-16", Efetivo = false, QtdaMin = 1001, QtdaMax = 2500, Valor = 6 },
                new QtdaGrupo() { CodigoGrupo = "C-16", Efetivo = false, QtdaMin = 2501, QtdaMax = 5000, Valor = 7 },
                new QtdaGrupo() { CodigoGrupo = "C-16", Efetivo = false, QtdaMin = 5001, QtdaMax = 10000, Valor = 9 },
                new QtdaGrupo() { CodigoGrupo = "C-17", Efetivo = true, QtdaMin = 0, QtdaMax = 19, Valor = 0 },
                new QtdaGrupo() { CodigoGrupo = "C-17", Efetivo = true, QtdaMin = 20, QtdaMax = 50, Valor = 1 },
                new QtdaGrupo() { CodigoGrupo = "C-17", Efetivo = true, QtdaMin = 51, QtdaMax = 100, Valor = 2 },
                new QtdaGrupo() { CodigoGrupo = "C-17", Efetivo = true, QtdaMin = 101, QtdaMax = 500, Valor = 4 },
                new QtdaGrupo() { CodigoGrupo = "C-17", Efetivo = true, QtdaMin = 501, QtdaMax = 1000, Valor = 6 },
                new QtdaGrupo() { CodigoGrupo = "C-17", Efetivo = true, QtdaMin = 1001, QtdaMax = 2500, Valor = 8 },
                new QtdaGrupo() { CodigoGrupo = "C-17", Efetivo = true, QtdaMin = 2501, QtdaMax = 5000, Valor = 10 },
                new QtdaGrupo() { CodigoGrupo = "C-17", Efetivo = true, QtdaMin = 5001, QtdaMax = 10000, Valor = 12 },
                new QtdaGrupo() { CodigoGrupo = "C-17", Efetivo = false, QtdaMin = 0, QtdaMax = 19, Valor = 0 },
                new QtdaGrupo() { CodigoGrupo = "C-17", Efetivo = false, QtdaMin = 20, QtdaMax = 50, Valor = 1 },
                new QtdaGrupo() { CodigoGrupo = "C-17", Efetivo = false, QtdaMin = 51, QtdaMax = 100, Valor = 2 },
                new QtdaGrupo() { CodigoGrupo = "C-17", Efetivo = false, QtdaMin = 101, QtdaMax = 300, Valor = 3 },
                new QtdaGrupo() { CodigoGrupo = "C-17", Efetivo = false, QtdaMin = 301, QtdaMax = 500, Valor = 4 },
                new QtdaGrupo() { CodigoGrupo = "C-17", Efetivo = false, QtdaMin = 501, QtdaMax = 1000, Valor = 5 },
                new QtdaGrupo() { CodigoGrupo = "C-17", Efetivo = false, QtdaMin = 1001, QtdaMax = 2500, Valor = 7 },
                new QtdaGrupo() { CodigoGrupo = "C-17", Efetivo = false, QtdaMin = 2501, QtdaMax = 5000, Valor = 8 },
                new QtdaGrupo() { CodigoGrupo = "C-17", Efetivo = false, QtdaMin = 5001, QtdaMax = 10000, Valor = 10 },
                new QtdaGrupo() { CodigoGrupo = "C-18", Efetivo = true, QtdaMin = 0, QtdaMax = 50, Valor = 0 },
                new QtdaGrupo() { CodigoGrupo = "C-18", Efetivo = true, QtdaMin = 51, QtdaMax = 100, Valor = 2 },
                new QtdaGrupo() { CodigoGrupo = "C-18", Efetivo = true, QtdaMin = 101, QtdaMax = 500, Valor = 4 },
                new QtdaGrupo() { CodigoGrupo = "C-18", Efetivo = true, QtdaMin = 501, QtdaMax = 1000, Valor = 6 },
                new QtdaGrupo() { CodigoGrupo = "C-18", Efetivo = true, QtdaMin = 1001, QtdaMax = 2500, Valor = 8 },
                new QtdaGrupo() { CodigoGrupo = "C-18", Efetivo = true, QtdaMin = 2501, QtdaMax = 5000, Valor = 10 },
                new QtdaGrupo() { CodigoGrupo = "C-18", Efetivo = true, QtdaMin = 5001, QtdaMax = 10000, Valor = 12 },
                new QtdaGrupo() { CodigoGrupo = "C-18", Efetivo = false, QtdaMin = 0, QtdaMax = 50, Valor = 0 },
                new QtdaGrupo() { CodigoGrupo = "C-18", Efetivo = false, QtdaMin = 51, QtdaMax = 100, Valor = 2 },
                new QtdaGrupo() { CodigoGrupo = "C-18", Efetivo = false, QtdaMin = 101, QtdaMax = 300, Valor = 3 },
                new QtdaGrupo() { CodigoGrupo = "C-18", Efetivo = false, QtdaMin = 301, QtdaMax = 500, Valor = 4 },
                new QtdaGrupo() { CodigoGrupo = "C-18", Efetivo = false, QtdaMin = 501, QtdaMax = 1000, Valor = 5 },
                new QtdaGrupo() { CodigoGrupo = "C-18", Efetivo = false, QtdaMin = 1001, QtdaMax = 2500, Valor = 7 },
                new QtdaGrupo() { CodigoGrupo = "C-18", Efetivo = false, QtdaMin = 2501, QtdaMax = 5000, Valor = 8 },
                new QtdaGrupo() { CodigoGrupo = "C-18", Efetivo = false, QtdaMin = 5001, QtdaMax = 10000, Valor = 10 },
                new QtdaGrupo() { CodigoGrupo = "C-18a", Efetivo = true, QtdaMin = 0, QtdaMax = 50, Valor = 0 },
                new QtdaGrupo() { CodigoGrupo = "C-18a", Efetivo = true, QtdaMin = 51, QtdaMax = 100, Valor = 3 },
                new QtdaGrupo() { CodigoGrupo = "C-18a", Efetivo = true, QtdaMin = 101, QtdaMax = 500, Valor = 4 },
                new QtdaGrupo() { CodigoGrupo = "C-18a", Efetivo = true, QtdaMin = 501, QtdaMax = 1000, Valor = 6 },
                new QtdaGrupo() { CodigoGrupo = "C-18a", Efetivo = true, QtdaMin = 1001, QtdaMax = 2500, Valor = 9 },
                new QtdaGrupo() { CodigoGrupo = "C-18a", Efetivo = true, QtdaMin = 2501, QtdaMax = 5000, Valor = 12 },
                new QtdaGrupo() { CodigoGrupo = "C-18a", Efetivo = true, QtdaMin = 5001, QtdaMax = 10000, Valor = 15 },
                new QtdaGrupo() { CodigoGrupo = "C-18a", Efetivo = false, QtdaMin = 0, QtdaMax = 50, Valor = 0 },
                new QtdaGrupo() { CodigoGrupo = "C-18a", Efetivo = false, QtdaMin = 51, QtdaMax = 300, Valor = 3 },
                new QtdaGrupo() { CodigoGrupo = "C-18a", Efetivo = false, QtdaMin = 301, QtdaMax = 500, Valor = 4 },
                new QtdaGrupo() { CodigoGrupo = "C-18a", Efetivo = false, QtdaMin = 501, QtdaMax = 1000, Valor = 5 },
                new QtdaGrupo() { CodigoGrupo = "C-18a", Efetivo = false, QtdaMin = 1001, QtdaMax = 2500, Valor = 7 },
                new QtdaGrupo() { CodigoGrupo = "C-18a", Efetivo = false, QtdaMin = 2501, QtdaMax = 5000, Valor = 9 },
                new QtdaGrupo() { CodigoGrupo = "C-18a", Efetivo = false, QtdaMin = 5001, QtdaMax = 10000, Valor = 12 },
                new QtdaGrupo() { CodigoGrupo = "C-19", Efetivo = true, QtdaMin = 0, QtdaMax = 50, Valor = 0 },
                new QtdaGrupo() { CodigoGrupo = "C-19", Efetivo = true, QtdaMin = 51, QtdaMax = 100, Valor = 1 },
                new QtdaGrupo() { CodigoGrupo = "C-19", Efetivo = true, QtdaMin = 101, QtdaMax = 300, Valor = 2 },
                new QtdaGrupo() { CodigoGrupo = "C-19", Efetivo = true, QtdaMin = 301, QtdaMax = 1000, Valor = 3 },
                new QtdaGrupo() { CodigoGrupo = "C-19", Efetivo = true, QtdaMin = 1001, QtdaMax = 2500, Valor = 4 },
                new QtdaGrupo() { CodigoGrupo = "C-19", Efetivo = true, QtdaMin = 2501, QtdaMax = 5000, Valor = 5 },
                new QtdaGrupo() { CodigoGrupo = "C-19", Efetivo = true, QtdaMin = 5001, QtdaMax = 10000, Valor = 6 },
                new QtdaGrupo() { CodigoGrupo = "C-19", Efetivo = false, QtdaMin = 0, QtdaMax = 50, Valor = 0 },
                new QtdaGrupo() { CodigoGrupo = "C-19", Efetivo = false, QtdaMin = 51, QtdaMax = 100, Valor = 1 },
                new QtdaGrupo() { CodigoGrupo = "C-19", Efetivo = false, QtdaMin = 101, QtdaMax = 300, Valor = 2 },
                new QtdaGrupo() { CodigoGrupo = "C-19", Efetivo = false, QtdaMin = 301, QtdaMax = 2500, Valor = 3 },
                new QtdaGrupo() { CodigoGrupo = "C-19", Efetivo = false, QtdaMin = 2501, QtdaMax = 10000, Valor = 4 },
                new QtdaGrupo() { CodigoGrupo = "C-20", Efetivo = true, QtdaMin = 0, QtdaMax = 29, Valor = 0 },
                new QtdaGrupo() { CodigoGrupo = "C-20", Efetivo = true, QtdaMin = 30, QtdaMax = 80, Valor = 1 },
                new QtdaGrupo() { CodigoGrupo = "C-20", Efetivo = true, QtdaMin = 81, QtdaMax = 300, Valor = 3 },
                new QtdaGrupo() { CodigoGrupo = "C-20", Efetivo = true, QtdaMin = 301, QtdaMax = 500, Valor = 4 },
                new QtdaGrupo() { CodigoGrupo = "C-20", Efetivo = true, QtdaMin = 501, QtdaMax = 2500, Valor = 5 },
                new QtdaGrupo() { CodigoGrupo = "C-20", Efetivo = true, QtdaMin = 2501, QtdaMax = 5000, Valor = 6 },
                new QtdaGrupo() { CodigoGrupo = "C-20", Efetivo = true, QtdaMin = 5001, QtdaMax = 10000, Valor = 8 },
                new QtdaGrupo() { CodigoGrupo = "C-20", Efetivo = false, QtdaMin = 0, QtdaMax = 29, Valor = 0 },
                new QtdaGrupo() { CodigoGrupo = "C-20", Efetivo = false, QtdaMin = 30, QtdaMax = 80, Valor = 1 },
                new QtdaGrupo() { CodigoGrupo = "C-20", Efetivo = false, QtdaMin = 81, QtdaMax = 500, Valor = 3 },
                new QtdaGrupo() { CodigoGrupo = "C-20", Efetivo = false, QtdaMin = 501, QtdaMax = 2500, Valor = 4 },
                new QtdaGrupo() { CodigoGrupo = "C-20", Efetivo = false, QtdaMin = 2501, QtdaMax = 5000, Valor = 5 },
                new QtdaGrupo() { CodigoGrupo = "C-20", Efetivo = false, QtdaMin = 5001, QtdaMax = 10000, Valor = 6 },
                new QtdaGrupo() { CodigoGrupo = "C-21", Efetivo = true, QtdaMin = 0, QtdaMax = 50, Valor = 0 },
                new QtdaGrupo() { CodigoGrupo = "C-21", Efetivo = true, QtdaMin = 51, QtdaMax = 100, Valor = 1 },
                new QtdaGrupo() { CodigoGrupo = "C-21", Efetivo = true, QtdaMin = 101, QtdaMax = 300, Valor = 2 },
                new QtdaGrupo() { CodigoGrupo = "C-21", Efetivo = true, QtdaMin = 301, QtdaMax = 1000, Valor = 3 },
                new QtdaGrupo() { CodigoGrupo = "C-21", Efetivo = true, QtdaMin = 1001, QtdaMax = 2500, Valor = 4 },
                new QtdaGrupo() { CodigoGrupo = "C-21", Efetivo = true, QtdaMin = 2501, QtdaMax = 5000, Valor = 5 },
                new QtdaGrupo() { CodigoGrupo = "C-21", Efetivo = true, QtdaMin = 5001, QtdaMax = 10000, Valor = 6 },
                new QtdaGrupo() { CodigoGrupo = "C-21", Efetivo = false, QtdaMin = 0, QtdaMax = 50, Valor = 0 },
                new QtdaGrupo() { CodigoGrupo = "C-21", Efetivo = false, QtdaMin = 51, QtdaMax = 100, Valor = 1 },
                new QtdaGrupo() { CodigoGrupo = "C-21", Efetivo = false, QtdaMin = 101, QtdaMax = 300, Valor = 2 },
                new QtdaGrupo() { CodigoGrupo = "C-21", Efetivo = false, QtdaMin = 301, QtdaMax = 2500, Valor = 3 },
                new QtdaGrupo() { CodigoGrupo = "C-21", Efetivo = false, QtdaMin = 2501, QtdaMax = 5000, Valor = 4 },
                new QtdaGrupo() { CodigoGrupo = "C-21", Efetivo = false, QtdaMin = 5001, QtdaMax = 10000, Valor = 5 },
                new QtdaGrupo() { CodigoGrupo = "C-22", Efetivo = true, QtdaMin = 0, QtdaMax = 19, Valor = 0 },
                new QtdaGrupo() { CodigoGrupo = "C-22", Efetivo = true, QtdaMin = 20, QtdaMax = 50, Valor = 1 },
                new QtdaGrupo() { CodigoGrupo = "C-22", Efetivo = true, QtdaMin = 51, QtdaMax = 100, Valor = 2 },
                new QtdaGrupo() { CodigoGrupo = "C-22", Efetivo = true, QtdaMin = 101, QtdaMax = 140, Valor = 3 },
                new QtdaGrupo() { CodigoGrupo = "C-22", Efetivo = true, QtdaMin = 141, QtdaMax = 500, Valor = 4 },
                new QtdaGrupo() { CodigoGrupo = "C-22", Efetivo = true, QtdaMin = 501, QtdaMax = 1000, Valor = 6 },
                new QtdaGrupo() { CodigoGrupo = "C-22", Efetivo = true, QtdaMin = 1001, QtdaMax = 2500, Valor = 8 },
                new QtdaGrupo() { CodigoGrupo = "C-22", Efetivo = true, QtdaMin = 2501, QtdaMax = 5000, Valor = 10 },
                new QtdaGrupo() { CodigoGrupo = "C-22", Efetivo = true, QtdaMin = 5001, QtdaMax = 10000, Valor = 12 },
                new QtdaGrupo() { CodigoGrupo = "C-22", Efetivo = false, QtdaMin = 0, QtdaMax = 19, Valor = 0 },
                new QtdaGrupo() { CodigoGrupo = "C-22", Efetivo = false, QtdaMin = 20, QtdaMax = 50, Valor = 1 },
                new QtdaGrupo() { CodigoGrupo = "C-22", Efetivo = false, QtdaMin = 51, QtdaMax = 100, Valor = 2 },
                new QtdaGrupo() { CodigoGrupo = "C-22", Efetivo = false, QtdaMin = 101, QtdaMax = 500, Valor = 3 },
                new QtdaGrupo() { CodigoGrupo = "C-22", Efetivo = false, QtdaMin = 501, QtdaMax = 1000, Valor = 5 },
                new QtdaGrupo() { CodigoGrupo = "C-22", Efetivo = false, QtdaMin = 1001, QtdaMax = 2500, Valor = 6 },
                new QtdaGrupo() { CodigoGrupo = "C-22", Efetivo = false, QtdaMin = 2501, QtdaMax = 5000, Valor = 8 },
                new QtdaGrupo() { CodigoGrupo = "C-22", Efetivo = false, QtdaMin = 5001, QtdaMax = 10000, Valor = 9 },
                new QtdaGrupo() { CodigoGrupo = "C-23", Efetivo = true, QtdaMin = 0, QtdaMax = 50, Valor = 0 },
                new QtdaGrupo() { CodigoGrupo = "C-23", Efetivo = true, QtdaMin = 51, QtdaMax = 100, Valor = 1 },
                new QtdaGrupo() { CodigoGrupo = "C-23", Efetivo = true, QtdaMin = 101, QtdaMax = 500, Valor = 2 },
                new QtdaGrupo() { CodigoGrupo = "C-23", Efetivo = true, QtdaMin = 501, QtdaMax = 1000, Valor = 3 },
                new QtdaGrupo() { CodigoGrupo = "C-23", Efetivo = true, QtdaMin = 1001, QtdaMax = 2500, Valor = 4 },
                new QtdaGrupo() { CodigoGrupo = "C-23", Efetivo = true, QtdaMin = 2501, QtdaMax = 5000, Valor = 5 },
                new QtdaGrupo() { CodigoGrupo = "C-23", Efetivo = true, QtdaMin = 5001, QtdaMax = 10000, Valor = 6 },
                new QtdaGrupo() { CodigoGrupo = "C-23", Efetivo = false, QtdaMin = 0, QtdaMax = 50, Valor = 0 },
                new QtdaGrupo() { CodigoGrupo = "C-23", Efetivo = false, QtdaMin = 51, QtdaMax = 100, Valor = 1 },
                new QtdaGrupo() { CodigoGrupo = "C-23", Efetivo = false, QtdaMin = 101, QtdaMax = 500, Valor = 2 },
                new QtdaGrupo() { CodigoGrupo = "C-23", Efetivo = false, QtdaMin = 501, QtdaMax = 2500, Valor = 3 },
                new QtdaGrupo() { CodigoGrupo = "C-23", Efetivo = false, QtdaMin = 2501, QtdaMax = 5000, Valor = 4 },
                new QtdaGrupo() { CodigoGrupo = "C-23", Efetivo = false, QtdaMin = 5001, QtdaMax = 10000, Valor = 5 },
                new QtdaGrupo() { CodigoGrupo = "C-24", Efetivo = true, QtdaMin = 0, QtdaMax = 19, Valor = 0 },
                new QtdaGrupo() { CodigoGrupo = "C-24", Efetivo = true, QtdaMin = 20, QtdaMax = 50, Valor = 1 },
                new QtdaGrupo() { CodigoGrupo = "C-24", Efetivo = true, QtdaMin = 51, QtdaMax = 100, Valor = 2 },
                new QtdaGrupo() { CodigoGrupo = "C-24", Efetivo = true, QtdaMin = 101, QtdaMax = 500, Valor = 4 },
                new QtdaGrupo() { CodigoGrupo = "C-24", Efetivo = true, QtdaMin = 501, QtdaMax = 1000, Valor = 6 },
                new QtdaGrupo() { CodigoGrupo = "C-24", Efetivo = true, QtdaMin = 1001, QtdaMax = 2500, Valor = 8 },
                new QtdaGrupo() { CodigoGrupo = "C-24", Efetivo = true, QtdaMin = 2501, QtdaMax = 5000, Valor = 10 },
                new QtdaGrupo() { CodigoGrupo = "C-24", Efetivo = true, QtdaMin = 5001, QtdaMax = 10000, Valor = 12 },
                new QtdaGrupo() { CodigoGrupo = "C-24", Efetivo = false, QtdaMin = 0, QtdaMax = 19, Valor = 0 },
                new QtdaGrupo() { CodigoGrupo = "C-24", Efetivo = false, QtdaMin = 20, QtdaMax = 50, Valor = 1 },
                new QtdaGrupo() { CodigoGrupo = "C-24", Efetivo = false, QtdaMin = 51, QtdaMax = 100, Valor = 2 },
                new QtdaGrupo() { CodigoGrupo = "C-24", Efetivo = false, QtdaMin = 101, QtdaMax = 140, Valor = 3 },
                new QtdaGrupo() { CodigoGrupo = "C-24", Efetivo = false, QtdaMin = 141, QtdaMax = 500, Valor = 4 },
                new QtdaGrupo() { CodigoGrupo = "C-24", Efetivo = false, QtdaMin = 501, QtdaMax = 1000, Valor = 5 },
                new QtdaGrupo() { CodigoGrupo = "C-24", Efetivo = false, QtdaMin = 1001, QtdaMax = 2500, Valor = 7 },
                new QtdaGrupo() { CodigoGrupo = "C-24", Efetivo = false, QtdaMin = 2501, QtdaMax = 5000, Valor = 8 },
                new QtdaGrupo() { CodigoGrupo = "C-24", Efetivo = false, QtdaMin = 5001, QtdaMax = 10000, Valor = 10 },
                new QtdaGrupo() { CodigoGrupo = "C-24a", Efetivo = true, QtdaMin = 0, QtdaMax = 50, Valor = 0 },
                new QtdaGrupo() { CodigoGrupo = "C-24a", Efetivo = true, QtdaMin = 51, QtdaMax = 100, Valor = 1 },
                new QtdaGrupo() { CodigoGrupo = "C-24a", Efetivo = true, QtdaMin = 101, QtdaMax = 500, Valor = 2 },
                new QtdaGrupo() { CodigoGrupo = "C-24a", Efetivo = true, QtdaMin = 501, QtdaMax = 1000, Valor = 3 },
                new QtdaGrupo() { CodigoGrupo = "C-24a", Efetivo = true, QtdaMin = 1001, QtdaMax = 2500, Valor = 4 },
                new QtdaGrupo() { CodigoGrupo = "C-24a", Efetivo = true, QtdaMin = 2501, QtdaMax = 5000, Valor = 5 },
                new QtdaGrupo() { CodigoGrupo = "C-24a", Efetivo = true, QtdaMin = 5001, QtdaMax = 10000, Valor = 6 },
                new QtdaGrupo() { CodigoGrupo = "C-24a", Efetivo = false, QtdaMin = 0, QtdaMax = 50, Valor = 0 },
                new QtdaGrupo() { CodigoGrupo = "C-24a", Efetivo = false, QtdaMin = 51, QtdaMax = 100, Valor = 1 },
                new QtdaGrupo() { CodigoGrupo = "C-24a", Efetivo = false, QtdaMin = 101, QtdaMax = 500, Valor = 2 },
                new QtdaGrupo() { CodigoGrupo = "C-24a", Efetivo = false, QtdaMin = 501, QtdaMax = 2500, Valor = 3 },
                new QtdaGrupo() { CodigoGrupo = "C-24a", Efetivo = false, QtdaMin = 2501, QtdaMax = 10000, Valor = 4 },
                new QtdaGrupo() { CodigoGrupo = "C-24b", Efetivo = true, QtdaMin = 0, QtdaMax = 19, Valor = 0 },
                new QtdaGrupo() { CodigoGrupo = "C-24b", Efetivo = true, QtdaMin = 20, QtdaMax = 50, Valor = 1 },
                new QtdaGrupo() { CodigoGrupo = "C-24b", Efetivo = true, QtdaMin = 51, QtdaMax = 100, Valor = 3 },
                new QtdaGrupo() { CodigoGrupo = "C-24b", Efetivo = true, QtdaMin = 101, QtdaMax = 500, Valor = 4 },
                new QtdaGrupo() { CodigoGrupo = "C-24b", Efetivo = true, QtdaMin = 501, QtdaMax = 1000, Valor = 6 },
                new QtdaGrupo() { CodigoGrupo = "C-24b", Efetivo = true, QtdaMin = 1001, QtdaMax = 2500, Valor = 9 },
                new QtdaGrupo() { CodigoGrupo = "C-24b", Efetivo = true, QtdaMin = 2501, QtdaMax = 5000, Valor = 12 },
                new QtdaGrupo() { CodigoGrupo = "C-24b", Efetivo = true, QtdaMin = 5001, QtdaMax = 10000, Valor = 15 },
                new QtdaGrupo() { CodigoGrupo = "C-24b", Efetivo = false, QtdaMin = 0, QtdaMax = 19, Valor = 0 },
                new QtdaGrupo() { CodigoGrupo = "C-24b", Efetivo = false, QtdaMin = 20, QtdaMax = 50, Valor = 1 },
                new QtdaGrupo() { CodigoGrupo = "C-24b", Efetivo = false, QtdaMin = 51, QtdaMax = 500, Valor = 3 },
                new QtdaGrupo() { CodigoGrupo = "C-24b", Efetivo = false, QtdaMin = 501, QtdaMax = 1000, Valor = 4 },
                new QtdaGrupo() { CodigoGrupo = "C-24b", Efetivo = false, QtdaMin = 1001, QtdaMax = 2500, Valor = 7 },
                new QtdaGrupo() { CodigoGrupo = "C-24b", Efetivo = false, QtdaMin = 2501, QtdaMax = 5000, Valor = 9 },
                new QtdaGrupo() { CodigoGrupo = "C-24b", Efetivo = false, QtdaMin = 5001, QtdaMax = 10000, Valor = 12 },
                new QtdaGrupo() { CodigoGrupo = "C-25", Efetivo = true, QtdaMin = 0, QtdaMax = 50, Valor = 0 },
                new QtdaGrupo() { CodigoGrupo = "C-25", Efetivo = true, QtdaMin = 51, QtdaMax = 100, Valor = 1 },
                new QtdaGrupo() { CodigoGrupo = "C-25", Efetivo = true, QtdaMin = 101, QtdaMax = 500, Valor = 2 },
                new QtdaGrupo() { CodigoGrupo = "C-25", Efetivo = true, QtdaMin = 501, QtdaMax = 1000, Valor = 3 },
                new QtdaGrupo() { CodigoGrupo = "C-25", Efetivo = true, QtdaMin = 1001, QtdaMax = 2500, Valor = 4 },
                new QtdaGrupo() { CodigoGrupo = "C-25", Efetivo = true, QtdaMin = 2501, QtdaMax = 5000, Valor = 5 },
                new QtdaGrupo() { CodigoGrupo = "C-25", Efetivo = true, QtdaMin = 5001, QtdaMax = 10000, Valor = 6 },
                new QtdaGrupo() { CodigoGrupo = "C-25", Efetivo = false, QtdaMin = 0, QtdaMax = 50, Valor = 0 },
                new QtdaGrupo() { CodigoGrupo = "C-25", Efetivo = false, QtdaMin = 51, QtdaMax = 100, Valor = 1 },
                new QtdaGrupo() { CodigoGrupo = "C-25", Efetivo = false, QtdaMin = 101, QtdaMax = 500, Valor = 2 },
                new QtdaGrupo() { CodigoGrupo = "C-25", Efetivo = false, QtdaMin = 501, QtdaMax = 2500, Valor = 3 },
                new QtdaGrupo() { CodigoGrupo = "C-25", Efetivo = false, QtdaMin = 2501, QtdaMax = 5000, Valor = 4 },
                new QtdaGrupo() { CodigoGrupo = "C-25", Efetivo = false, QtdaMin = 5001, QtdaMax = 10000, Valor = 5 },
                new QtdaGrupo() { CodigoGrupo = "C-26", Efetivo = true, QtdaMin = 0, QtdaMax = 300, Valor = 0 },
                new QtdaGrupo() { CodigoGrupo = "C-26", Efetivo = true, QtdaMin = 301, QtdaMax = 500, Valor = 1 },
                new QtdaGrupo() { CodigoGrupo = "C-26", Efetivo = true, QtdaMin = 501, QtdaMax = 1000, Valor = 2 },
                new QtdaGrupo() { CodigoGrupo = "C-26", Efetivo = true, QtdaMin = 1001, QtdaMax = 2500, Valor = 3 },
                new QtdaGrupo() { CodigoGrupo = "C-26", Efetivo = true, QtdaMin = 2501, QtdaMax = 5000, Valor = 4 },
                new QtdaGrupo() { CodigoGrupo = "C-26", Efetivo = true, QtdaMin = 5001, QtdaMax = 10000, Valor = 5 },
                new QtdaGrupo() { CodigoGrupo = "C-26", Efetivo = false, QtdaMin = 0, QtdaMax = 300, Valor = 0 },
                new QtdaGrupo() { CodigoGrupo = "C-26", Efetivo = false, QtdaMin = 301, QtdaMax = 500, Valor = 1 },
                new QtdaGrupo() { CodigoGrupo = "C-26", Efetivo = false, QtdaMin = 501, QtdaMax = 1000, Valor = 2 },
                new QtdaGrupo() { CodigoGrupo = "C-26", Efetivo = false, QtdaMin = 1001, QtdaMax = 5000, Valor = 3 },
                new QtdaGrupo() { CodigoGrupo = "C-26", Efetivo = false, QtdaMin = 5001, QtdaMax = 10000, Valor = 4 },
                new QtdaGrupo() { CodigoGrupo = "C-27", Efetivo = true, QtdaMin = 0, QtdaMax = 100, Valor = 0 },
                new QtdaGrupo() { CodigoGrupo = "C-27", Efetivo = true, QtdaMin = 101, QtdaMax = 140, Valor = 1 },
                new QtdaGrupo() { CodigoGrupo = "C-27", Efetivo = true, QtdaMin = 141, QtdaMax = 300, Valor = 2 },
                new QtdaGrupo() { CodigoGrupo = "C-27", Efetivo = true, QtdaMin = 301, QtdaMax = 500, Valor = 3 },
                new QtdaGrupo() { CodigoGrupo = "C-27", Efetivo = true, QtdaMin = 501, QtdaMax = 1000, Valor = 4 },
                new QtdaGrupo() { CodigoGrupo = "C-27", Efetivo = true, QtdaMin = 1001, QtdaMax = 2500, Valor = 5 },
                new QtdaGrupo() { CodigoGrupo = "C-27", Efetivo = true, QtdaMin = 2501, QtdaMax = 10000, Valor = 6 },
                new QtdaGrupo() { CodigoGrupo = "C-27", Efetivo = false, QtdaMin = 0, QtdaMax = 100, Valor = 0 },
                new QtdaGrupo() { CodigoGrupo = "C-27", Efetivo = false, QtdaMin = 101, QtdaMax = 140, Valor = 1 },
                new QtdaGrupo() { CodigoGrupo = "C-27", Efetivo = false, QtdaMin = 141, QtdaMax = 300, Valor = 2 },
                new QtdaGrupo() { CodigoGrupo = "C-27", Efetivo = false, QtdaMin = 301, QtdaMax = 1000, Valor = 3 },
                new QtdaGrupo() { CodigoGrupo = "C-27", Efetivo = false, QtdaMin = 1001, QtdaMax = 2500, Valor = 4 },
                new QtdaGrupo() { CodigoGrupo = "C-27", Efetivo = false, QtdaMin = 2501, QtdaMax = 10000, Valor = 5 },
                new QtdaGrupo() { CodigoGrupo = "C-28", Efetivo = true, QtdaMin = 0, QtdaMax = 100, Valor = 0 },
                new QtdaGrupo() { CodigoGrupo = "C-28", Efetivo = true, QtdaMin = 101, QtdaMax = 140, Valor = 1 },
                new QtdaGrupo() { CodigoGrupo = "C-28", Efetivo = true, QtdaMin = 141, QtdaMax = 300, Valor = 2 },
                new QtdaGrupo() { CodigoGrupo = "C-28", Efetivo = true, QtdaMin = 301, QtdaMax = 500, Valor = 3 },
                new QtdaGrupo() { CodigoGrupo = "C-28", Efetivo = true, QtdaMin = 501, QtdaMax = 1000, Valor = 4 },
                new QtdaGrupo() { CodigoGrupo = "C-28", Efetivo = true, QtdaMin = 1001, QtdaMax = 2500, Valor = 5 },
                new QtdaGrupo() { CodigoGrupo = "C-28", Efetivo = true, QtdaMin = 2501, QtdaMax = 10000, Valor = 6 },
                new QtdaGrupo() { CodigoGrupo = "C-28", Efetivo = false, QtdaMin = 0, QtdaMax = 100, Valor = 0 },
                new QtdaGrupo() { CodigoGrupo = "C-28", Efetivo = false, QtdaMin = 101, QtdaMax = 140, Valor = 1 },
                new QtdaGrupo() { CodigoGrupo = "C-28", Efetivo = false, QtdaMin = 141, QtdaMax = 300, Valor = 2 },
                new QtdaGrupo() { CodigoGrupo = "C-28", Efetivo = false, QtdaMin = 301, QtdaMax = 500, Valor = 3 },
                new QtdaGrupo() { CodigoGrupo = "C-28", Efetivo = false, QtdaMin = 501, QtdaMax = 1000, Valor = 4 },
                new QtdaGrupo() { CodigoGrupo = "C-28", Efetivo = false, QtdaMin = 1001, QtdaMax = 10000, Valor = 5 },
                new QtdaGrupo() { CodigoGrupo = "C-29", Efetivo = true, QtdaMin = 0, QtdaMax = 300, Valor = 0 },
                new QtdaGrupo() { CodigoGrupo = "C-29", Efetivo = true, QtdaMin = 301, QtdaMax = 500, Valor = 1 },
                new QtdaGrupo() { CodigoGrupo = "C-29", Efetivo = true, QtdaMin = 501, QtdaMax = 1000, Valor = 2 },
                new QtdaGrupo() { CodigoGrupo = "C-29", Efetivo = true, QtdaMin = 1001, QtdaMax = 2500, Valor = 3 },
                new QtdaGrupo() { CodigoGrupo = "C-29", Efetivo = true, QtdaMin = 2501, QtdaMax = 5000, Valor = 4 },
                new QtdaGrupo() { CodigoGrupo = "C-29", Efetivo = true, QtdaMin = 5001, QtdaMax = 10000, Valor = 5 },
                new QtdaGrupo() { CodigoGrupo = "C-29", Efetivo = false, QtdaMin = 0, QtdaMax = 300, Valor = 0 },
                new QtdaGrupo() { CodigoGrupo = "C-29", Efetivo = false, QtdaMin = 301, QtdaMax = 500, Valor = 1 },
                new QtdaGrupo() { CodigoGrupo = "C-29", Efetivo = false, QtdaMin = 501, QtdaMax = 1000, Valor = 2 },
                new QtdaGrupo() { CodigoGrupo = "C-29", Efetivo = false, QtdaMin = 1001, QtdaMax = 5000, Valor = 3 },
                new QtdaGrupo() { CodigoGrupo = "C-29", Efetivo = false, QtdaMin = 5001, QtdaMax = 10000, Valor = 4 },
                new QtdaGrupo() { CodigoGrupo = "C-30", Efetivo = true, QtdaMin = 0, QtdaMax = 19, Valor = 0 },
                new QtdaGrupo() { CodigoGrupo = "C-30", Efetivo = true, QtdaMin = 20, QtdaMax = 80, Valor = 1 },
                new QtdaGrupo() { CodigoGrupo = "C-30", Efetivo = true, QtdaMin = 81, QtdaMax = 100, Valor = 2 },
                new QtdaGrupo() { CodigoGrupo = "C-30", Efetivo = true, QtdaMin = 101, QtdaMax = 300, Valor = 4 },
                new QtdaGrupo() { CodigoGrupo = "C-30", Efetivo = true, QtdaMin = 301, QtdaMax = 500, Valor = 5 },
                new QtdaGrupo() { CodigoGrupo = "C-30", Efetivo = true, QtdaMin = 501, QtdaMax = 1000, Valor = 7 },
                new QtdaGrupo() { CodigoGrupo = "C-30", Efetivo = true, QtdaMin = 1001, QtdaMax = 2500, Valor = 8 },
                new QtdaGrupo() { CodigoGrupo = "C-30", Efetivo = true, QtdaMin = 2501, QtdaMax = 5000, Valor = 9 },
                new QtdaGrupo() { CodigoGrupo = "C-30", Efetivo = true, QtdaMin = 5001, QtdaMax = 10000, Valor = 10 },
                new QtdaGrupo() { CodigoGrupo = "C-30", Efetivo = false, QtdaMin = 0, QtdaMax = 19, Valor = 0 },
                new QtdaGrupo() { CodigoGrupo = "C-30", Efetivo = false, QtdaMin = 20, QtdaMax = 80, Valor = 1 },
                new QtdaGrupo() { CodigoGrupo = "C-30", Efetivo = false, QtdaMin = 81, QtdaMax = 100, Valor = 2 },
                new QtdaGrupo() { CodigoGrupo = "C-30", Efetivo = false, QtdaMin = 101, QtdaMax = 140, Valor = 3 },
                new QtdaGrupo() { CodigoGrupo = "C-30", Efetivo = false, QtdaMin = 141, QtdaMax = 500, Valor = 4 },
                new QtdaGrupo() { CodigoGrupo = "C-30", Efetivo = false, QtdaMin = 501, QtdaMax = 1000, Valor = 6 },
                new QtdaGrupo() { CodigoGrupo = "C-30", Efetivo = false, QtdaMin = 1001, QtdaMax = 2500, Valor = 7 },
                new QtdaGrupo() { CodigoGrupo = "C-30", Efetivo = false, QtdaMin = 2501, QtdaMax = 5000, Valor = 8 },
                new QtdaGrupo() { CodigoGrupo = "C-30", Efetivo = false, QtdaMin = 5001, QtdaMax = 10000, Valor = 9 },
                new QtdaGrupo() { CodigoGrupo = "C-31", Efetivo = true, QtdaMin = 0, QtdaMax = 50, Valor = 0 },
                new QtdaGrupo() { CodigoGrupo = "C-31", Efetivo = true, QtdaMin = 51, QtdaMax = 100, Valor = 1 },
                new QtdaGrupo() { CodigoGrupo = "C-31", Efetivo = true, QtdaMin = 101, QtdaMax = 300, Valor = 2 },
                new QtdaGrupo() { CodigoGrupo = "C-31", Efetivo = true, QtdaMin = 301, QtdaMax = 1000, Valor = 3 },
                new QtdaGrupo() { CodigoGrupo = "C-31", Efetivo = true, QtdaMin = 1001, QtdaMax = 2500, Valor = 4 },
                new QtdaGrupo() { CodigoGrupo = "C-31", Efetivo = true, QtdaMin = 2501, QtdaMax = 5000, Valor = 5 },
                new QtdaGrupo() { CodigoGrupo = "C-31", Efetivo = true, QtdaMin = 5001, QtdaMax = 10000, Valor = 6 },
                new QtdaGrupo() { CodigoGrupo = "C-31", Efetivo = false, QtdaMin = 0, QtdaMax = 50, Valor = 0 },
                new QtdaGrupo() { CodigoGrupo = "C-31", Efetivo = false, QtdaMin = 51, QtdaMax = 100, Valor = 1 },
                new QtdaGrupo() { CodigoGrupo = "C-31", Efetivo = false, QtdaMin = 101, QtdaMax = 300, Valor = 2 },
                new QtdaGrupo() { CodigoGrupo = "C-31", Efetivo = false, QtdaMin = 301, QtdaMax = 2500, Valor = 3 },
                new QtdaGrupo() { CodigoGrupo = "C-31", Efetivo = false, QtdaMin = 2501, QtdaMax = 5000, Valor = 4 },
                new QtdaGrupo() { CodigoGrupo = "C-31", Efetivo = false, QtdaMin = 5001, QtdaMax = 10000, Valor = 5 },
                new QtdaGrupo() { CodigoGrupo = "C-32", Efetivo = true, QtdaMin = 0, QtdaMax = 50, Valor = 0 },
                new QtdaGrupo() { CodigoGrupo = "C-32", Efetivo = true, QtdaMin = 51, QtdaMax = 100, Valor = 1 },
                new QtdaGrupo() { CodigoGrupo = "C-32", Efetivo = true, QtdaMin = 101, QtdaMax = 300, Valor = 2 },
                new QtdaGrupo() { CodigoGrupo = "C-32", Efetivo = true, QtdaMin = 301, QtdaMax = 1000, Valor = 3 },
                new QtdaGrupo() { CodigoGrupo = "C-32", Efetivo = true, QtdaMin = 1001, QtdaMax = 2500, Valor = 4 },
                new QtdaGrupo() { CodigoGrupo = "C-32", Efetivo = true, QtdaMin = 2501, QtdaMax = 5000, Valor = 5 },
                new QtdaGrupo() { CodigoGrupo = "C-32", Efetivo = true, QtdaMin = 5001, QtdaMax = 10000, Valor = 6 },
                new QtdaGrupo() { CodigoGrupo = "C-32", Efetivo = false, QtdaMin = 0, QtdaMax = 50, Valor = 0 },
                new QtdaGrupo() { CodigoGrupo = "C-32", Efetivo = false, QtdaMin = 51, QtdaMax = 100, Valor = 1 },
                new QtdaGrupo() { CodigoGrupo = "C-32", Efetivo = false, QtdaMin = 101, QtdaMax = 300, Valor = 2 },
                new QtdaGrupo() { CodigoGrupo = "C-32", Efetivo = false, QtdaMin = 301, QtdaMax = 2500, Valor = 3 },
                new QtdaGrupo() { CodigoGrupo = "C-32", Efetivo = false, QtdaMin = 2501, QtdaMax = 5000, Valor = 4 },
                new QtdaGrupo() { CodigoGrupo = "C-32", Efetivo = false, QtdaMin = 5001, QtdaMax = 10000, Valor = 5 },
                new QtdaGrupo() { CodigoGrupo = "C-33", Efetivo = true, QtdaMin = 0, QtdaMax = 100, Valor = 0 },
                new QtdaGrupo() { CodigoGrupo = "C-33", Efetivo = true, QtdaMin = 101, QtdaMax = 500, Valor = 1 },
                new QtdaGrupo() { CodigoGrupo = "C-33", Efetivo = true, QtdaMin = 501, QtdaMax = 1000, Valor = 2 },
                new QtdaGrupo() { CodigoGrupo = "C-33", Efetivo = true, QtdaMin = 1001, QtdaMax = 2500, Valor = 3 },
                new QtdaGrupo() { CodigoGrupo = "C-33", Efetivo = true, QtdaMin = 2501, QtdaMax = 5000, Valor = 4 },
                new QtdaGrupo() { CodigoGrupo = "C-33", Efetivo = true, QtdaMin = 5001, QtdaMax = 10000, Valor = 5 },
                new QtdaGrupo() { CodigoGrupo = "C-33", Efetivo = false, QtdaMin = 0, QtdaMax = 100, Valor = 0 },
                new QtdaGrupo() { CodigoGrupo = "C-33", Efetivo = false, QtdaMin = 101, QtdaMax = 500, Valor = 1 },
                new QtdaGrupo() { CodigoGrupo = "C-33", Efetivo = false, QtdaMin = 501, QtdaMax = 1000, Valor = 2 },
                new QtdaGrupo() { CodigoGrupo = "C-33", Efetivo = false, QtdaMin = 1001, QtdaMax = 5000, Valor = 3 },
                new QtdaGrupo() { CodigoGrupo = "C-33", Efetivo = false, QtdaMin = 5001, QtdaMax = 10000, Valor = 4 },
                new QtdaGrupo() { CodigoGrupo = "C-34", Efetivo = true, QtdaMin = 0, QtdaMax = 19, Valor = 0 },
                new QtdaGrupo() { CodigoGrupo = "C-34", Efetivo = true, QtdaMin = 20, QtdaMax = 50, Valor = 1 },
                new QtdaGrupo() { CodigoGrupo = "C-34", Efetivo = true, QtdaMin = 51, QtdaMax = 100, Valor = 2 },
                new QtdaGrupo() { CodigoGrupo = "C-34", Efetivo = true, QtdaMin = 101, QtdaMax = 500, Valor = 4 },
                new QtdaGrupo() { CodigoGrupo = "C-34", Efetivo = true, QtdaMin = 501, QtdaMax = 1000, Valor = 6 },
                new QtdaGrupo() { CodigoGrupo = "C-34", Efetivo = true, QtdaMin = 1001, QtdaMax = 2500, Valor = 8 },
                new QtdaGrupo() { CodigoGrupo = "C-34", Efetivo = true, QtdaMin = 2501, QtdaMax = 5000, Valor = 10 },
                new QtdaGrupo() { CodigoGrupo = "C-34", Efetivo = true, QtdaMin = 5001, QtdaMax = 10000, Valor = 12 },
                new QtdaGrupo() { CodigoGrupo = "C-34", Efetivo = false, QtdaMin = 0, QtdaMax = 19, Valor = 0 },
                new QtdaGrupo() { CodigoGrupo = "C-34", Efetivo = false, QtdaMin = 20, QtdaMax = 50, Valor = 1 },
                new QtdaGrupo() { CodigoGrupo = "C-34", Efetivo = false, QtdaMin = 51, QtdaMax = 100, Valor = 2 },
                new QtdaGrupo() { CodigoGrupo = "C-34", Efetivo = false, QtdaMin = 101, QtdaMax = 300, Valor = 3 },
                new QtdaGrupo() { CodigoGrupo = "C-34", Efetivo = false, QtdaMin = 301, QtdaMax = 500, Valor = 4 },
                new QtdaGrupo() { CodigoGrupo = "C-34", Efetivo = false, QtdaMin = 501, QtdaMax = 1000, Valor = 5 },
                new QtdaGrupo() { CodigoGrupo = "C-34", Efetivo = false, QtdaMin = 1001, QtdaMax = 2500, Valor = 7 },
                new QtdaGrupo() { CodigoGrupo = "C-34", Efetivo = false, QtdaMin = 2501, QtdaMax = 5000, Valor = 8 },
                new QtdaGrupo() { CodigoGrupo = "C-34", Efetivo = false, QtdaMin = 5001, QtdaMax = 10000, Valor = 9 },
                new QtdaGrupo() { CodigoGrupo = "C-35", Efetivo = true, QtdaMin = 0, QtdaMax = 50, Valor = 0 },
                new QtdaGrupo() { CodigoGrupo = "C-35", Efetivo = true, QtdaMin = 51, QtdaMax = 100, Valor = 1 },
                new QtdaGrupo() { CodigoGrupo = "C-35", Efetivo = true, QtdaMin = 101, QtdaMax = 500, Valor = 2 },
                new QtdaGrupo() { CodigoGrupo = "C-35", Efetivo = true, QtdaMin = 501, QtdaMax = 1000, Valor = 3 },
                new QtdaGrupo() { CodigoGrupo = "C-35", Efetivo = true, QtdaMin = 1001, QtdaMax = 2500, Valor = 4 },
                new QtdaGrupo() { CodigoGrupo = "C-35", Efetivo = true, QtdaMin = 2501, QtdaMax = 5000, Valor = 5 },
                new QtdaGrupo() { CodigoGrupo = "C-35", Efetivo = true, QtdaMin = 5001, QtdaMax = 10000, Valor = 6 },
                new QtdaGrupo() { CodigoGrupo = "C-35", Efetivo = false, QtdaMin = 0, QtdaMax = 50, Valor = 0 },
                new QtdaGrupo() { CodigoGrupo = "C-35", Efetivo = false, QtdaMin = 51, QtdaMax = 100, Valor = 1 },
                new QtdaGrupo() { CodigoGrupo = "C-35", Efetivo = false, QtdaMin = 101, QtdaMax = 500, Valor = 2 },
                new QtdaGrupo() { CodigoGrupo = "C-35", Efetivo = false, QtdaMin = 501, QtdaMax = 2500, Valor = 3 },
                new QtdaGrupo() { CodigoGrupo = "C-35", Efetivo = false, QtdaMin = 2501, QtdaMax = 5000, Valor = 4 },
                new QtdaGrupo() { CodigoGrupo = "C-35", Efetivo = false, QtdaMin = 5001, QtdaMax = 10000, Valor = 5 }
            );
        }
    }
}
